-- ============================================================================
-- CRUCIPUZZLE — SCHEMA SUPABASE (PostgreSQL)
-- ============================================================================
-- Struttura speculare al modello Prisma/SQLite usato in locale:
--
--   languages ──< categories ──< words
--                    │
--                    └── parent_id (self-ref) => sottocategorie opzionali
--
-- Fonte dati unica: data/wordbank.json
--   • in locale   -> prisma/seed.ts            (bun prisma/seed.ts)
--   • su Supabase -> supabase/seed-wordbank.sql (generato: node scripts/export-wordbank-sql.mjs)
--
-- Le stesse API del gioco (/api/wordbanks, /api/words) funzionano su entrambi:
-- basta sostituire il client Prisma con il client Supabase in src/lib/db.ts.
--
-- Convenzioni dati:
--   words.text    = forma per la griglia: MAIUSCOLO, solo lettere Unicode,
--                   senza spazi/apostrofi, accenti MANTENUTI (É Ü Ñ ...),
--                   œ→OE, ß→SS
--   words.display = forma naturale maiuscola CON spazi ("TENDINE D'ACHILLE"),
--                   NULL quando coincide con text
--   words.concept_key = chiave del concetto nel JSON, allineata fra le lingue
--                   (es. 'persone.muscoli.12') — utile per sincronizzazione
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Tabella lingue
-- ----------------------------------------------------------------------------
create table if not exists public.languages (
  id         smallint primary key,
  code       text not null unique,          -- 'it' | 'en' | 'fr' | 'de' | 'es'
  name       text not null,                 -- 'Italiano'
  emoji      text not null,                 -- '🇮🇹'
  sort_order smallint not null default 0
);

-- ----------------------------------------------------------------------------
-- Tabella categorie (con sottocategorie via parent_id)
-- ----------------------------------------------------------------------------
create table if not exists public.categories (
  id          bigint generated by default as identity primary key,
  language_id smallint not null references public.languages(id) on delete cascade,
  parent_id   bigint references public.categories(id) on delete cascade, -- NULL = radice
  slug        text not null,                -- univoco per lingua
  name        text not null,
  description text not null default '',
  emoji       text not null default '',
  color       text not null default '',     -- classi Tailwind della tile
  is_new      boolean not null default false,
  sort_order  integer not null default 0,
  created_at  timestamptz not null default now(),

  unique (language_id, slug)
);

create index if not exists categories_language_idx on public.categories (language_id);
create index if not exists categories_parent_idx   on public.categories (parent_id);

-- ----------------------------------------------------------------------------
-- Tabella parole
-- ----------------------------------------------------------------------------
create table if not exists public.words (
  id          bigint generated by default as identity primary key,
  category_id bigint not null references public.categories(id) on delete cascade,
  text        text not null,                -- forma per la griglia
  display     text,                         -- forma naturale (opzionale)
  difficulty  text not null default 'medium' check (difficulty in ('easy','medium','hard')),
  concept_key text,                         -- chiave concetto nel JSON (cross-lingua)
  created_at  timestamptz not null default now()
);

create index if not exists words_category_idx on public.words (category_id);
create index if not exists words_text_idx     on public.words (text);

-- ----------------------------------------------------------------------------
-- Row Level Security: lettura pubblica (anon), scrittura solo service_role
-- ----------------------------------------------------------------------------
alter table public.languages  enable row level security;
alter table public.categories enable row level security;
alter table public.words      enable row level security;

drop policy if exists "public read languages"  on public.languages;
drop policy if exists "public read categories" on public.categories;
drop policy if exists "public read words"      on public.words;

create policy "public read languages"  on public.languages  for select using (true);
create policy "public read categories" on public.categories for select using (true);
create policy "public read words"      on public.words      for select using (true);
-- Nessuna policy di insert/update/delete: restano al service_role (chiave segreta).

-- ----------------------------------------------------------------------------
-- View di comodo: categorie con conteggio parole distinte (radice = anche figlie)
-- Riproduce la risposta di GET /api/wordbanks
-- ----------------------------------------------------------------------------
create or replace view public.v_wordbanks as
select
  l.code                                   as language_code,
  l.name                                   as language_name,
  l.emoji                                  as language_emoji,
  c.id,
  c.slug,
  c.name,
  c.description,
  c.emoji                                  as category_emoji,
  c.color,
  c.is_new,
  c.sort_order,
  c.parent_id,
  (select count(distinct w.text)
     from public.words w
    where w.category_id = c.id
       or w.category_id in (select cc.id from public.categories cc where cc.parent_id = c.id)
  )                                        as word_count
from public.categories c
join public.languages l on l.id = c.language_id
order by l.sort_order, c.sort_order;
