-- ============================================================
-- CRUCIPUZZLE — SEED SUPABASE (generato automaticamente)
-- Fonte: data/wordbank.json — NON modificare a mano
-- Generato da scripts/export-wordbank-sql.mjs
-- ============================================================
begin;

delete from public.words;
delete from public.categories;
delete from public.languages;

insert into public.languages (id, code, name, emoji, sort_order) values
  (1, 'it', 'Italiano', '🇮🇹', 1),
  (2, 'en', 'English', '🇬🇧', 2),
  (3, 'fr', 'Français', '🇫🇷', 3),
  (4, 'de', 'Deutsch', '🇩🇪', 4),
  (5, 'es', 'Español', '🇪🇸', 5);

insert into public.categories (id, language_id, parent_id, slug, name, description, emoji, color, is_new, sort_order) values
  (1, 1, null, 'animali', 'Animali', 'Dal giardino di casa alla savana', '🦁', 'bg-amber-100 text-amber-900 border-amber-300', false, 0),
  (2, 1, null, 'frutta-verdura', 'Frutta & Verdura', 'Il mercato contadino in una griglia', '🍎', 'bg-lime-100 text-lime-900 border-lime-300', false, 1),
  (3, 1, null, 'cibo', 'Cibo', 'Un menù degustazione di parole', '🍝', 'bg-orange-100 text-orange-900 border-orange-300', false, 2),
  (4, 1, null, 'nazioni', 'Nazioni', 'Un giro del mondo in 12x12', '🌍', 'bg-emerald-100 text-emerald-900 border-emerald-300', false, 3),
  (5, 1, null, 'colori', 'Colori', 'La tavolozza nascosta', '🎨', 'bg-rose-100 text-rose-900 border-rose-300', false, 4),
  (6, 1, null, 'sport', 'Sport', 'Podio, record e sudore', '🏆', 'bg-teal-100 text-teal-900 border-teal-300', false, 5),
  (7, 1, null, 'corpo-umano', 'Corpo Umano', 'Piccola anatomia tra le celle', '🫀', 'bg-red-100 text-red-900 border-red-300', false, 6),
  (8, 1, null, 'citta', 'Città Italiane', 'Da Nord a Sud, capoluoghi e non solo', '🏛️', 'bg-stone-100 text-stone-900 border-stone-300', false, 7),
  (9, 1, null, 'natura', 'Natura & Meteo', 'Cieli, boschi e stagioni', '🌦️', 'bg-sky-100 text-sky-900 border-sky-300', false, 8),
  (10, 1, null, 'casa', 'Casa', 'Oggetti quotidiani ben nascosti', '🏠', 'bg-yellow-100 text-yellow-900 border-yellow-300', false, 9),
  (11, 1, null, 'musica', 'Musica', 'Note, strumenti e ritmi', '🎵', 'bg-fuchsia-100 text-fuchsia-900 border-fuchsia-300', false, 10),
  (12, 1, null, 'lavori', 'Lavori & Mestieri', 'Chi fa cosa nella griglia', '👷', 'bg-cyan-100 text-cyan-900 border-cyan-300', false, 11),
  (13, 2, null, 'animals', 'Animals', 'From the backyard to the savanna', '🦁', 'bg-amber-100 text-amber-900 border-amber-300', false, 12),
  (14, 2, null, 'food', 'Food', 'A tasting menu of words', '🍔', 'bg-orange-100 text-orange-900 border-orange-300', false, 13),
  (15, 2, null, 'countries', 'Countries', 'A world tour in a grid', '🌍', 'bg-emerald-100 text-emerald-900 border-emerald-300', false, 14),
  (16, 1, null, 'persone', 'Persone', 'Il corpo umano dal viso ai piedi', '🧑', 'bg-violet-100 text-violet-900 border-violet-300', true, 15),
  (17, 1, 16, 'persone--corpo', 'Corpo', '', '🧍', 'bg-violet-100 text-violet-900 border-violet-300', true, 0),
  (18, 1, 16, 'persone--viso', 'Viso', '', '😊', 'bg-violet-100 text-violet-900 border-violet-300', true, 1),
  (19, 1, 16, 'persone--mano', 'Mano', '', '✋', 'bg-violet-100 text-violet-900 border-violet-300', true, 2),
  (20, 1, 16, 'persone--piede', 'Piede', '', '🦶', 'bg-violet-100 text-violet-900 border-violet-300', true, 3),
  (21, 1, 16, 'persone--muscoli', 'Muscoli', '', '💪', 'bg-violet-100 text-violet-900 border-violet-300', true, 4),
  (22, 1, 16, 'persone--scheletro', 'Scheletro', '', '🦴', 'bg-violet-100 text-violet-900 border-violet-300', true, 5),
  (23, 1, 16, 'persone--organi-interni', 'Organi interni', '', '🫀', 'bg-violet-100 text-violet-900 border-violet-300', true, 6),
  (24, 1, 16, 'persone--testa', 'Testa', '', '🧠', 'bg-violet-100 text-violet-900 border-violet-300', true, 7),
  (25, 1, 16, 'persone--sistemi-corporei', 'Sistemi corporei', '', '🩺', 'bg-violet-100 text-violet-900 border-violet-300', true, 8),
  (26, 1, 16, 'persone--organi-riproduttivi', 'Organi riproduttivi', '', '🧬', 'bg-violet-100 text-violet-900 border-violet-300', true, 9),
  (27, 1, 16, 'persone--contraccezione', 'Contraccezione', '', '💊', 'bg-violet-100 text-violet-900 border-violet-300', true, 10),
  (28, 2, null, 'persone', 'People', 'The human body from head to toe', '🧑', 'bg-violet-100 text-violet-900 border-violet-300', true, 15),
  (29, 2, 28, 'persone--corpo', 'Body', '', '🧍', 'bg-violet-100 text-violet-900 border-violet-300', true, 0),
  (30, 2, 28, 'persone--viso', 'Face', '', '😊', 'bg-violet-100 text-violet-900 border-violet-300', true, 1),
  (31, 2, 28, 'persone--mano', 'Hand', '', '✋', 'bg-violet-100 text-violet-900 border-violet-300', true, 2),
  (32, 2, 28, 'persone--piede', 'Foot', '', '🦶', 'bg-violet-100 text-violet-900 border-violet-300', true, 3),
  (33, 2, 28, 'persone--muscoli', 'Muscles', '', '💪', 'bg-violet-100 text-violet-900 border-violet-300', true, 4),
  (34, 2, 28, 'persone--scheletro', 'Skeleton', '', '🦴', 'bg-violet-100 text-violet-900 border-violet-300', true, 5),
  (35, 2, 28, 'persone--organi-interni', 'Internal organs', '', '🫀', 'bg-violet-100 text-violet-900 border-violet-300', true, 6),
  (36, 2, 28, 'persone--testa', 'Head', '', '🧠', 'bg-violet-100 text-violet-900 border-violet-300', true, 7),
  (37, 2, 28, 'persone--sistemi-corporei', 'Body systems', '', '🩺', 'bg-violet-100 text-violet-900 border-violet-300', true, 8),
  (38, 2, 28, 'persone--organi-riproduttivi', 'Reproductive organs', '', '🧬', 'bg-violet-100 text-violet-900 border-violet-300', true, 9),
  (39, 2, 28, 'persone--contraccezione', 'Contraception', '', '💊', 'bg-violet-100 text-violet-900 border-violet-300', true, 10),
  (40, 3, null, 'persone', 'Gens', 'Le corps humain de la tête aux pieds', '🧑', 'bg-violet-100 text-violet-900 border-violet-300', true, 15),
  (41, 3, 40, 'persone--corpo', 'Corps', '', '🧍', 'bg-violet-100 text-violet-900 border-violet-300', true, 0),
  (42, 3, 40, 'persone--viso', 'Visage', '', '😊', 'bg-violet-100 text-violet-900 border-violet-300', true, 1),
  (43, 3, 40, 'persone--mano', 'Main', '', '✋', 'bg-violet-100 text-violet-900 border-violet-300', true, 2),
  (44, 3, 40, 'persone--piede', 'Pied', '', '🦶', 'bg-violet-100 text-violet-900 border-violet-300', true, 3),
  (45, 3, 40, 'persone--muscoli', 'Muscles', '', '💪', 'bg-violet-100 text-violet-900 border-violet-300', true, 4),
  (46, 3, 40, 'persone--scheletro', 'Squelette', '', '🦴', 'bg-violet-100 text-violet-900 border-violet-300', true, 5),
  (47, 3, 40, 'persone--organi-interni', 'Organes internes', '', '🫀', 'bg-violet-100 text-violet-900 border-violet-300', true, 6),
  (48, 3, 40, 'persone--testa', 'Tête', '', '🧠', 'bg-violet-100 text-violet-900 border-violet-300', true, 7),
  (49, 3, 40, 'persone--sistemi-corporei', 'Systèmes du corps', '', '🩺', 'bg-violet-100 text-violet-900 border-violet-300', true, 8),
  (50, 3, 40, 'persone--organi-riproduttivi', 'Organes reproducteurs', '', '🧬', 'bg-violet-100 text-violet-900 border-violet-300', true, 9);

insert into public.categories (id, language_id, parent_id, slug, name, description, emoji, color, is_new, sort_order) values
  (51, 3, 40, 'persone--contraccezione', 'Contraception', '', '💊', 'bg-violet-100 text-violet-900 border-violet-300', true, 10),
  (52, 4, null, 'persone', 'Menschen', 'Der menschliche Körper von Kopf bis Fuß', '🧑', 'bg-violet-100 text-violet-900 border-violet-300', true, 15),
  (53, 4, 52, 'persone--corpo', 'Körper', '', '🧍', 'bg-violet-100 text-violet-900 border-violet-300', true, 0),
  (54, 4, 52, 'persone--viso', 'Gesicht', '', '😊', 'bg-violet-100 text-violet-900 border-violet-300', true, 1),
  (55, 4, 52, 'persone--mano', 'Hand', '', '✋', 'bg-violet-100 text-violet-900 border-violet-300', true, 2),
  (56, 4, 52, 'persone--piede', 'Fuß', '', '🦶', 'bg-violet-100 text-violet-900 border-violet-300', true, 3),
  (57, 4, 52, 'persone--muscoli', 'Muskeln', '', '💪', 'bg-violet-100 text-violet-900 border-violet-300', true, 4),
  (58, 4, 52, 'persone--scheletro', 'Skelett', '', '🦴', 'bg-violet-100 text-violet-900 border-violet-300', true, 5),
  (59, 4, 52, 'persone--organi-interni', 'Innere Organe', '', '🫀', 'bg-violet-100 text-violet-900 border-violet-300', true, 6),
  (60, 4, 52, 'persone--testa', 'Kopf', '', '🧠', 'bg-violet-100 text-violet-900 border-violet-300', true, 7),
  (61, 4, 52, 'persone--sistemi-corporei', 'Körpersysteme', '', '🩺', 'bg-violet-100 text-violet-900 border-violet-300', true, 8),
  (62, 4, 52, 'persone--organi-riproduttivi', 'Fortpflanzungsorgane', '', '🧬', 'bg-violet-100 text-violet-900 border-violet-300', true, 9),
  (63, 4, 52, 'persone--contraccezione', 'Empfängnisverhütung', '', '💊', 'bg-violet-100 text-violet-900 border-violet-300', true, 10),
  (64, 5, null, 'persone', 'Gente', 'El cuerpo humano de la cabeza a los pies', '🧑', 'bg-violet-100 text-violet-900 border-violet-300', true, 15),
  (65, 5, 64, 'persone--corpo', 'Cuerpo', '', '🧍', 'bg-violet-100 text-violet-900 border-violet-300', true, 0),
  (66, 5, 64, 'persone--viso', 'Cara', '', '😊', 'bg-violet-100 text-violet-900 border-violet-300', true, 1),
  (67, 5, 64, 'persone--mano', 'Mano', '', '✋', 'bg-violet-100 text-violet-900 border-violet-300', true, 2),
  (68, 5, 64, 'persone--piede', 'Pie', '', '🦶', 'bg-violet-100 text-violet-900 border-violet-300', true, 3),
  (69, 5, 64, 'persone--muscoli', 'Músculos', '', '💪', 'bg-violet-100 text-violet-900 border-violet-300', true, 4),
  (70, 5, 64, 'persone--scheletro', 'Esqueleto', '', '🦴', 'bg-violet-100 text-violet-900 border-violet-300', true, 5),
  (71, 5, 64, 'persone--organi-interni', 'Órganos internos', '', '🫀', 'bg-violet-100 text-violet-900 border-violet-300', true, 6),
  (72, 5, 64, 'persone--testa', 'Cabeza', '', '🧠', 'bg-violet-100 text-violet-900 border-violet-300', true, 7),
  (73, 5, 64, 'persone--sistemi-corporei', 'Sistemas corporales', '', '🩺', 'bg-violet-100 text-violet-900 border-violet-300', true, 8),
  (74, 5, 64, 'persone--organi-riproduttivi', 'Órganos reproductores', '', '🧬', 'bg-violet-100 text-violet-900 border-violet-300', true, 9),
  (75, 5, 64, 'persone--contraccezione', 'Anticoncepción', '', '💊', 'bg-violet-100 text-violet-900 border-violet-300', true, 10);

insert into public.words (category_id, text, display, difficulty, concept_key) values
  (1, 'LEONE', null, 'easy', null),
  (1, 'TIGRE', null, 'easy', null),
  (1, 'ZEBRA', null, 'easy', null),
  (1, 'CANE', null, 'easy', null),
  (1, 'GATTO', null, 'easy', null),
  (1, 'CAVALLO', null, 'medium', null),
  (1, 'MUCCA', null, 'easy', null),
  (1, 'PECORA', null, 'medium', null),
  (1, 'CAPRA', null, 'easy', null),
  (1, 'GALLINA', null, 'medium', null),
  (1, 'ANATRA', null, 'medium', null),
  (1, 'CONIGLIO', null, 'medium', null),
  (1, 'LEPRE', null, 'easy', null),
  (1, 'VOLPE', null, 'easy', null),
  (1, 'ORSO', null, 'easy', null),
  (1, 'LUPO', null, 'easy', null),
  (1, 'CERVO', null, 'easy', null),
  (1, 'GIRAFFA', null, 'medium', null),
  (1, 'ELEFANTE', null, 'medium', null),
  (1, 'SCIMMIA', null, 'medium', null),
  (1, 'DELFINO', null, 'medium', null),
  (1, 'BALENA', null, 'medium', null),
  (1, 'SQUALO', null, 'medium', null),
  (1, 'TONNO', null, 'easy', null),
  (1, 'AQUILA', null, 'medium', null),
  (1, 'FALCO', null, 'easy', null),
  (1, 'GUFO', null, 'easy', null),
  (1, 'CIGNO', null, 'easy', null),
  (1, 'PASSERO', null, 'medium', null),
  (1, 'PAPPAGALLO', null, 'hard', null),
  (1, 'RICCIO', null, 'medium', null),
  (1, 'FARFALLA', null, 'medium', null),
  (1, 'GRILLO', null, 'medium', null),
  (1, 'RAGNO', null, 'easy', null),
  (1, 'SERPENTE', null, 'medium', null),
  (1, 'LUCERTOLA', null, 'hard', null),
  (1, 'TARTARUGA', null, 'hard', null),
  (1, 'RANA', null, 'easy', null),
  (1, 'CANGURO', null, 'medium', null),
  (1, 'PANDA', null, 'easy', null),
  (1, 'KOALA', null, 'easy', null),
  (1, 'CAMMELLO', null, 'medium', null),
  (1, 'LINCE', null, 'easy', null),
  (1, 'STAMBECCO', null, 'hard', null),
  (1, 'ISTICE', null, 'medium', null),
  (1, 'GHEPARDO', null, 'medium', null),
  (2, 'MELA', null, 'easy', null),
  (2, 'PERA', null, 'easy', null),
  (2, 'BANANA', null, 'medium', null),
  (2, 'ARANCIA', null, 'medium', null),
  (2, 'LIMONE', null, 'medium', null),
  (2, 'FRAGOLA', null, 'medium', null),
  (2, 'CILIEGIA', null, 'medium', null),
  (2, 'ALBICOCCA', null, 'hard', null),
  (2, 'PESCA', null, 'easy', null),
  (2, 'UVA', null, 'easy', null),
  (2, 'FICO', null, 'easy', null),
  (2, 'MELONE', null, 'medium', null),
  (2, 'ANGURIA', null, 'medium', null),
  (2, 'MANDORLA', null, 'medium', null),
  (2, 'NOCE', null, 'easy', null),
  (2, 'CASTAGNA', null, 'medium', null),
  (2, 'PATATA', null, 'medium', null),
  (2, 'CAROTA', null, 'medium', null),
  (2, 'POMODORO', null, 'medium', null),
  (2, 'ZUCCHINA', null, 'medium', null),
  (2, 'MELANZANA', null, 'hard', null),
  (2, 'PEPERONE', null, 'medium', null),
  (2, 'CIPOLLA', null, 'medium', null),
  (2, 'AGLIO', null, 'easy', null),
  (2, 'LATTUGA', null, 'medium', null),
  (2, 'SPINACI', null, 'medium', null),
  (2, 'BROCCOLO', null, 'medium', null),
  (2, 'CAVOLFIORE', null, 'hard', null),
  (2, 'FINOCCHIO', null, 'hard', null),
  (2, 'SEDANO', null, 'medium', null),
  (2, 'RAVANELLO', null, 'hard', null),
  (2, 'ASPARAGO', null, 'medium', null),
  (2, 'FUNGO', null, 'easy', null),
  (2, 'TARTUFO', null, 'medium', null),
  (2, 'RUCOLA', null, 'medium', null),
  (2, 'BASILICO', null, 'medium', null),
  (2, 'PREZZEMOLO', null, 'hard', null),
  (2, 'SALVIA', null, 'medium', null),
  (2, 'ROSMARINO', null, 'hard', null),
  (2, 'MELAGRANA', null, 'hard', null),
  (2, 'PAPAIA', null, 'medium', null),
  (2, 'KAKI', null, 'easy', null),
  (2, 'LITCHI', null, 'medium', null),
  (3, 'PASTA', null, 'easy', null),
  (3, 'PIZZA', null, 'easy', null),
  (3, 'RISO', null, 'easy', null),
  (3, 'PANE', null, 'easy', null),
  (3, 'LASAGNE', null, 'medium', null),
  (3, 'GNOCCHI', null, 'medium', null),
  (3, 'RAVIOLI', null, 'medium', null),
  (3, 'TORTELLINI', null, 'hard', null),
  (3, 'SPAGHETTI', null, 'hard', null),
  (3, 'RISOTTO', null, 'medium', null),
  (3, 'POLLO', null, 'easy', null);

insert into public.words (category_id, text, display, difficulty, concept_key) values
  (3, 'BISTECCA', null, 'medium', null),
  (3, 'SALSICCIA', null, 'hard', null),
  (3, 'PROSCIUTTO', null, 'hard', null),
  (3, 'SALAME', null, 'medium', null),
  (3, 'MOZZARELLA', null, 'hard', null),
  (3, 'PARMIGIANO', null, 'hard', null),
  (3, 'GORGONZOLA', null, 'hard', null),
  (3, 'RICOTTA', null, 'medium', null),
  (3, 'BURRO', null, 'easy', null),
  (3, 'FORMAGGIO', null, 'hard', null),
  (3, 'GELATO', null, 'medium', null),
  (3, 'TORTA', null, 'easy', null),
  (3, 'BISCOTTI', null, 'medium', null),
  (3, 'CIOCCOLATO', null, 'hard', null),
  (3, 'CARAMELLE', null, 'hard', null),
  (3, 'MARMELLATA', null, 'hard', null),
  (3, 'MIELE', null, 'easy', null),
  (3, 'ZUCCHERO', null, 'medium', null),
  (3, 'PEPE', null, 'easy', null),
  (3, 'OLIO', null, 'easy', null),
  (3, 'ACETO', null, 'easy', null),
  (3, 'PANETTONE', null, 'hard', null),
  (3, 'TIRAMISU', null, 'medium', null),
  (3, 'CROSTATA', null, 'medium', null),
  (3, 'BRIOCHE', null, 'medium', null),
  (3, 'CANNOLI', null, 'medium', null),
  (3, 'ARANCINI', null, 'medium', null),
  (3, 'PESTO', null, 'easy', null),
  (3, 'RAGU', null, 'easy', null),
  (3, 'ABBACCHIO', null, 'hard', null),
  (4, 'ITALIA', null, 'medium', null),
  (4, 'FRANCIA', null, 'medium', null),
  (4, 'SPAGNA', null, 'medium', null),
  (4, 'PORTOGALLO', null, 'hard', null),
  (4, 'GERMANIA', null, 'medium', null),
  (4, 'AUSTRIA', null, 'medium', null),
  (4, 'SVIZZERA', null, 'medium', null),
  (4, 'OLANDA', null, 'medium', null),
  (4, 'BELGIO', null, 'medium', null),
  (4, 'IRLANDA', null, 'medium', null),
  (4, 'DANIMARCA', null, 'hard', null),
  (4, 'SVEZIA', null, 'medium', null),
  (4, 'NORVEGIA', null, 'medium', null),
  (4, 'FINLANDIA', null, 'hard', null),
  (4, 'POLONIA', null, 'medium', null),
  (4, 'RUSSIA', null, 'medium', null),
  (4, 'UCRAINA', null, 'medium', null),
  (4, 'GRECIA', null, 'medium', null),
  (4, 'TURCHIA', null, 'medium', null),
  (4, 'EGITTO', null, 'medium', null),
  (4, 'MAROCCO', null, 'medium', null),
  (4, 'TUNISIA', null, 'medium', null),
  (4, 'ALGERIA', null, 'medium', null),
  (4, 'NIGERIA', null, 'medium', null),
  (4, 'AMERICA', null, 'medium', null),
  (4, 'CANADA', null, 'medium', null),
  (4, 'MESSICO', null, 'medium', null),
  (4, 'BRASILE', null, 'medium', null),
  (4, 'ARGENTINA', null, 'hard', null),
  (4, 'CILE', null, 'easy', null),
  (4, 'PERU', null, 'easy', null),
  (4, 'BOLIVIA', null, 'medium', null),
  (4, 'CUBA', null, 'easy', null),
  (4, 'GIAPPONE', null, 'medium', null),
  (4, 'CINA', null, 'easy', null),
  (4, 'INDIA', null, 'easy', null),
  (4, 'COREA', null, 'easy', null),
  (4, 'VIETNAM', null, 'medium', null),
  (4, 'THAILANDIA', null, 'hard', null),
  (4, 'AUSTRALIA', null, 'hard', null),
  (4, 'GROENLANDIA', null, 'hard', null),
  (4, 'ISLANDA', null, 'medium', null),
  (5, 'ROSSO', null, 'easy', null),
  (5, 'GIALLO', null, 'medium', null),
  (5, 'VERDE', null, 'easy', null),
  (5, 'VIOLA', null, 'easy', null),
  (5, 'ROSA', null, 'easy', null),
  (5, 'MARRONE', null, 'medium', null),
  (5, 'GRIGIO', null, 'medium', null),
  (5, 'NERO', null, 'easy', null),
  (5, 'BIANCO', null, 'medium', null),
  (5, 'ORO', null, 'easy', null),
  (5, 'ARGENTO', null, 'medium', null),
  (5, 'TURCHESE', null, 'medium', null),
  (5, 'INDACO', null, 'medium', null),
  (5, 'MAGENTA', null, 'medium', null),
  (5, 'BEIGE', null, 'easy', null),
  (5, 'PORPORA', null, 'medium', null),
  (5, 'SMERALDO', null, 'medium', null),
  (5, 'AMBRA', null, 'easy', null),
  (5, 'CORALLO', null, 'medium', null),
  (5, 'AVORIO', null, 'medium', null),
  (5, 'EBANO', null, 'easy', null),
  (5, 'AMARANTO', null, 'medium', null),
  (5, 'LILLA', null, 'easy', null),
  (5, 'ZAFFERANO', null, 'hard', null),
  (5, 'CREMISI', null, 'medium', null),
  (5, 'OCRA', null, 'easy', null),
  (6, 'CALCIO', null, 'medium', null),
  (6, 'PALLONE', null, 'medium', null);

insert into public.words (category_id, text, display, difficulty, concept_key) values
  (6, 'TENNIS', null, 'medium', null),
  (6, 'NUOTO', null, 'easy', null),
  (6, 'ATLETICA', null, 'medium', null),
  (6, 'PUGILATO', null, 'medium', null),
  (6, 'SCHERMA', null, 'medium', null),
  (6, 'CICLISMO', null, 'medium', null),
  (6, 'CORSA', null, 'easy', null),
  (6, 'MARATONA', null, 'medium', null),
  (6, 'SCI', null, 'easy', null),
  (6, 'PALESTRA', null, 'medium', null),
  (6, 'PADEL', null, 'easy', null),
  (6, 'GOLF', null, 'easy', null),
  (6, 'RUGBY', null, 'easy', null),
  (6, 'BASEBALL', null, 'medium', null),
  (6, 'PALLANUOTO', null, 'hard', null),
  (6, 'PALLAVOLO', null, 'hard', null),
  (6, 'GINNASTICA', null, 'hard', null),
  (6, 'EQUITAZIONE', null, 'hard', null),
  (6, 'CANOA', null, 'easy', null),
  (6, 'VELA', null, 'easy', null),
  (6, 'BOXE', null, 'easy', null),
  (6, 'LOTTA', null, 'easy', null),
  (6, 'SALTO', null, 'easy', null),
  (6, 'OSTACOLI', null, 'medium', null),
  (6, 'BICICLETTA', null, 'hard', null),
  (6, 'MARCIA', null, 'medium', null),
  (6, 'ARCIERE', null, 'medium', null),
  (6, 'PIROETTA', null, 'medium', null),
  (6, 'SLALOM', null, 'medium', null),
  (6, 'TRIPLO', null, 'medium', null),
  (6, 'MARTELLO', null, 'medium', null),
  (6, 'GIAVELLOTTO', null, 'hard', null),
  (7, 'TESTA', null, 'easy', null),
  (7, 'OCCHIO', null, 'medium', null),
  (7, 'NASO', null, 'easy', null),
  (7, 'BOCCA', null, 'easy', null),
  (7, 'DENTI', null, 'easy', null),
  (7, 'LINGUA', null, 'medium', null),
  (7, 'LABBRA', null, 'medium', null),
  (7, 'ORECCHIO', null, 'medium', null),
  (7, 'COLLO', null, 'easy', null),
  (7, 'SPALLA', null, 'medium', null),
  (7, 'BRACCIO', null, 'medium', null),
  (7, 'GOMITO', null, 'medium', null),
  (7, 'MANO', null, 'easy', null),
  (7, 'DITO', null, 'easy', null),
  (7, 'POLSO', null, 'easy', null),
  (7, 'TORACE', null, 'medium', null),
  (7, 'PETTO', null, 'easy', null),
  (7, 'COSTOLE', null, 'medium', null),
  (7, 'SCHIENA', null, 'medium', null),
  (7, 'GINOCCHIO', null, 'hard', null),
  (7, 'COSCIA', null, 'medium', null),
  (7, 'POLPACCIO', null, 'hard', null),
  (7, 'CAVIGLIA', null, 'medium', null),
  (7, 'PIEDE', null, 'easy', null),
  (7, 'TALLONE', null, 'medium', null),
  (7, 'CUORE', null, 'easy', null),
  (7, 'POLMONI', null, 'medium', null),
  (7, 'FEGATO', null, 'medium', null),
  (7, 'STOMACO', null, 'medium', null),
  (7, 'RENI', null, 'easy', null),
  (7, 'CERVELLO', null, 'medium', null),
  (7, 'SANGUE', null, 'medium', null),
  (7, 'OSSA', null, 'easy', null),
  (7, 'MUSCOLI', null, 'medium', null),
  (7, 'PELLE', null, 'easy', null),
  (7, 'CAPELLI', null, 'medium', null),
  (7, 'BARBA', null, 'easy', null),
  (7, 'UNGHIE', null, 'medium', null),
  (7, 'INTESTINO', null, 'hard', null),
  (8, 'ROMA', null, 'easy', null),
  (8, 'MILANO', null, 'medium', null),
  (8, 'NAPOLI', null, 'medium', null),
  (8, 'TORINO', null, 'medium', null),
  (8, 'PALERMO', null, 'medium', null),
  (8, 'GENOVA', null, 'medium', null),
  (8, 'BOLOGNA', null, 'medium', null),
  (8, 'FIRENZE', null, 'medium', null),
  (8, 'BARI', null, 'easy', null),
  (8, 'CATANIA', null, 'medium', null),
  (8, 'VENEZIA', null, 'medium', null),
  (8, 'VERONA', null, 'medium', null),
  (8, 'PISA', null, 'easy', null),
  (8, 'SIENA', null, 'easy', null),
  (8, 'TRIESTE', null, 'medium', null),
  (8, 'TRENTO', null, 'medium', null),
  (8, 'UDINE', null, 'easy', null),
  (8, 'PARMA', null, 'easy', null),
  (8, 'MODENA', null, 'medium', null),
  (8, 'FERRARA', null, 'medium', null),
  (8, 'RAVENNA', null, 'medium', null),
  (8, 'RIMINI', null, 'medium', null),
  (8, 'ANCONA', null, 'medium', null),
  (8, 'PERUGIA', null, 'medium', null),
  (8, 'PESCARA', null, 'medium', null),
  (8, 'CAMPOBASSO', null, 'hard', null),
  (8, 'CASERTA', null, 'medium', null),
  (8, 'BENEVENTO', null, 'hard', null),
  (8, 'POTENZA', null, 'medium', null);

insert into public.words (category_id, text, display, difficulty, concept_key) values
  (8, 'COSENZA', null, 'medium', null),
  (8, 'CATANZARO', null, 'hard', null),
  (8, 'MESSINA', null, 'medium', null),
  (8, 'SASSARI', null, 'medium', null),
  (8, 'CAGLIARI', null, 'medium', null),
  (8, 'NUORO', null, 'easy', null),
  (8, 'ORISTANO', null, 'medium', null),
  (8, 'AOSTA', null, 'easy', null),
  (8, 'LECCE', null, 'easy', null),
  (8, 'TARANTO', null, 'medium', null),
  (8, 'BRINDISI', null, 'medium', null),
  (8, 'FOGGIA', null, 'medium', null),
  (8, 'TERNI', null, 'easy', null),
  (8, 'MATERA', null, 'medium', null),
  (8, 'LAMEZIA', null, 'medium', null),
  (8, 'OLBIA', null, 'easy', null),
  (8, 'SIRACUSA', null, 'medium', null),
  (8, 'AGRIGENTO', null, 'hard', null),
  (9, 'PIOGGIA', null, 'medium', null),
  (9, 'NEVE', null, 'easy', null),
  (9, 'VENTO', null, 'easy', null),
  (9, 'TEMPESTA', null, 'medium', null),
  (9, 'FOGHINA', null, 'medium', null),
  (9, 'NUVOLE', null, 'medium', null),
  (9, 'SOLE', null, 'easy', null),
  (9, 'LUNA', null, 'easy', null),
  (9, 'STELLE', null, 'medium', null),
  (9, 'ARCOBALENO', null, 'hard', null),
  (9, 'TUONO', null, 'easy', null),
  (9, 'FULMINE', null, 'medium', null),
  (9, 'GRANDINE', null, 'medium', null),
  (9, 'BRINA', null, 'easy', null),
  (9, 'GHIACCIO', null, 'medium', null),
  (9, 'BRUMA', null, 'easy', null),
  (9, 'CALDO', null, 'easy', null),
  (9, 'FREDDO', null, 'medium', null),
  (9, 'PRIMAVERA', null, 'hard', null),
  (9, 'ESTATE', null, 'medium', null),
  (9, 'AUTUNNO', null, 'medium', null),
  (9, 'INVERNO', null, 'medium', null),
  (9, 'MARE', null, 'easy', null),
  (9, 'MONTAGNA', null, 'medium', null),
  (9, 'FIUME', null, 'easy', null),
  (9, 'LAGO', null, 'easy', null),
  (9, 'BOSCO', null, 'easy', null),
  (9, 'FORESTA', null, 'medium', null),
  (9, 'DESERTO', null, 'medium', null),
  (9, 'VULCANO', null, 'medium', null),
  (9, 'ISOLA', null, 'easy', null),
  (9, 'VALLE', null, 'easy', null),
  (9, 'GHIACCIAIO', null, 'hard', null),
  (9, 'CASCATA', null, 'medium', null),
  (9, 'PRATO', null, 'easy', null),
  (9, 'SPIAGGIA', null, 'medium', null),
  (10, 'PORTA', null, 'easy', null),
  (10, 'FINESTRA', null, 'medium', null),
  (10, 'TAVOLO', null, 'medium', null),
  (10, 'SEDIA', null, 'easy', null),
  (10, 'DIVANO', null, 'medium', null),
  (10, 'LETTO', null, 'easy', null),
  (10, 'CUCINA', null, 'medium', null),
  (10, 'SALOTTO', null, 'medium', null),
  (10, 'BAGNO', null, 'easy', null),
  (10, 'SPECCHIO', null, 'medium', null),
  (10, 'ARMADIO', null, 'medium', null),
  (10, 'CASSETTI', null, 'medium', null),
  (10, 'LAMPADA', null, 'medium', null),
  (10, 'TAPPETO', null, 'medium', null),
  (10, 'CUSCINO', null, 'medium', null),
  (10, 'SPOGLIATOIO', null, 'hard', null),
  (10, 'FORCHETTA', null, 'hard', null),
  (10, 'COLTELLO', null, 'medium', null),
  (10, 'CUCCHIAIO', null, 'hard', null),
  (10, 'PIATTO', null, 'medium', null),
  (10, 'BICCHIERE', null, 'hard', null),
  (10, 'PENTOLA', null, 'medium', null),
  (10, 'PADELLA', null, 'medium', null),
  (10, 'FORNO', null, 'easy', null),
  (10, 'FRIGORIFERO', null, 'hard', null),
  (10, 'LAVATRICE', null, 'hard', null),
  (10, 'SCOPA', null, 'easy', null),
  (10, 'ASPIRAPOLVERE', null, 'hard', null),
  (10, 'TENDA', null, 'easy', null),
  (10, 'SERRATURA', null, 'hard', null),
  (10, 'CAMINO', null, 'medium', null),
  (11, 'NOTA', null, 'easy', null),
  (11, 'MUSICA', null, 'medium', null),
  (11, 'CANZONE', null, 'medium', null),
  (11, 'MELODIA', null, 'medium', null),
  (11, 'RITMO', null, 'easy', null),
  (11, 'CORO', null, 'easy', null),
  (11, 'ORCHESTRA', null, 'hard', null),
  (11, 'PIANOFORTE', null, 'hard', null),
  (11, 'VIOLINO', null, 'medium', null),
  (11, 'VIOLONCELLO', null, 'hard', null),
  (11, 'CHITARRA', null, 'medium', null),
  (11, 'BASSO', null, 'easy', null),
  (11, 'BATTERIA', null, 'medium', null),
  (11, 'TAMBURELLO', null, 'hard', null),
  (11, 'TROMBA', null, 'medium', null);

insert into public.words (category_id, text, display, difficulty, concept_key) values
  (11, 'SAXOFONO', null, 'medium', null),
  (11, 'FLAUTO', null, 'medium', null),
  (11, 'CLARINETTO', null, 'hard', null),
  (11, 'ARPA', null, 'easy', null),
  (11, 'ORGANO', null, 'medium', null),
  (11, 'ACCORDO', null, 'medium', null),
  (11, 'SCALA', null, 'easy', null),
  (11, 'OPERA', null, 'easy', null),
  (11, 'SINFONIA', null, 'medium', null),
  (11, 'CONCERTO', null, 'medium', null),
  (11, 'MICROFONO', null, 'hard', null),
  (11, 'CASSE', null, 'easy', null),
  (11, 'DISCO', null, 'easy', null),
  (12, 'MEDICO', null, 'medium', null),
  (12, 'INFERMIERE', null, 'hard', null),
  (12, 'AVVOCATO', null, 'medium', null),
  (12, 'GIUDICE', null, 'medium', null),
  (12, 'NOTAIO', null, 'medium', null),
  (12, 'INSEGNANTE', null, 'hard', null),
  (12, 'STUDENTE', null, 'medium', null),
  (12, 'INGEGNERE', null, 'hard', null),
  (12, 'ARCHITETTO', null, 'hard', null),
  (12, 'GEOMETRA', null, 'medium', null),
  (12, 'ELETTRICISTA', null, 'hard', null),
  (12, 'IDRAULICO', null, 'hard', null),
  (12, 'MURATORE', null, 'medium', null),
  (12, 'CARPENTIERE', null, 'hard', null),
  (12, 'FALEGNAME', null, 'hard', null),
  (12, 'PANETTIERE', null, 'hard', null),
  (12, 'MACELLAIO', null, 'hard', null),
  (12, 'PESCATORE', null, 'hard', null),
  (12, 'CONTADINO', null, 'hard', null),
  (12, 'PASTORE', null, 'medium', null),
  (12, 'BARBIERE', null, 'medium', null),
  (12, 'PARRUCCHIERA', null, 'hard', null),
  (12, 'SARTO', null, 'easy', null),
  (12, 'CALZOLAIO', null, 'hard', null),
  (12, 'OREFICE', null, 'medium', null),
  (12, 'COMMERCIANTE', null, 'hard', null),
  (12, 'CASSIERA', null, 'medium', null),
  (12, 'CAMERIERE', null, 'hard', null),
  (12, 'CUOCO', null, 'easy', null),
  (12, 'PILOTA', null, 'medium', null),
  (12, 'VIGILE', null, 'medium', null),
  (12, 'VIGILFUOCO', null, 'hard', null),
  (12, 'GIORNALISTA', null, 'hard', null),
  (12, 'FOTOGRAFO', null, 'hard', null),
  (13, 'LION', null, 'easy', null),
  (13, 'TIGER', null, 'easy', null),
  (13, 'ZEBRA', null, 'easy', null),
  (13, 'DOG', null, 'easy', null),
  (13, 'CAT', null, 'easy', null),
  (13, 'HORSE', null, 'easy', null),
  (13, 'COW', null, 'easy', null),
  (13, 'SHEEP', null, 'easy', null),
  (13, 'GOAT', null, 'easy', null),
  (13, 'CHICKEN', null, 'medium', null),
  (13, 'DUCK', null, 'easy', null),
  (13, 'RABBIT', null, 'medium', null),
  (13, 'HARE', null, 'easy', null),
  (13, 'FOX', null, 'easy', null),
  (13, 'BEAR', null, 'easy', null),
  (13, 'WOLF', null, 'easy', null),
  (13, 'DEER', null, 'easy', null),
  (13, 'GIRAFFE', null, 'medium', null),
  (13, 'ELEPHANT', null, 'medium', null),
  (13, 'MONKEY', null, 'medium', null),
  (13, 'DOLPHIN', null, 'medium', null),
  (13, 'WHALE', null, 'easy', null),
  (13, 'SHARK', null, 'easy', null),
  (13, 'EAGLE', null, 'easy', null),
  (13, 'FALCON', null, 'medium', null),
  (13, 'OWL', null, 'easy', null),
  (13, 'SWAN', null, 'easy', null),
  (13, 'SPARROW', null, 'medium', null),
  (13, 'PARROT', null, 'medium', null),
  (13, 'HEDGEHOG', null, 'medium', null),
  (13, 'BUTTERFLY', null, 'hard', null),
  (13, 'SNAKE', null, 'easy', null),
  (13, 'TURTLE', null, 'medium', null),
  (13, 'FROG', null, 'easy', null),
  (13, 'KANGAROO', null, 'medium', null),
  (13, 'PANDA', null, 'easy', null),
  (13, 'KOALA', null, 'easy', null),
  (13, 'CAMEL', null, 'easy', null),
  (14, 'BREAD', null, 'easy', null),
  (14, 'PASTA', null, 'easy', null),
  (14, 'PIZZA', null, 'easy', null),
  (14, 'RICE', null, 'easy', null),
  (14, 'CHEESE', null, 'medium', null),
  (14, 'BUTTER', null, 'medium', null),
  (14, 'HONEY', null, 'easy', null),
  (14, 'SUGAR', null, 'easy', null),
  (14, 'APPLE', null, 'easy', null),
  (14, 'BANANA', null, 'medium', null),
  (14, 'ORANGE', null, 'medium', null),
  (14, 'LEMON', null, 'easy', null),
  (14, 'CHERRY', null, 'medium', null),
  (14, 'GRAPE', null, 'easy', null),
  (14, 'POTATO', null, 'medium', null);

insert into public.words (category_id, text, display, difficulty, concept_key) values
  (14, 'CARROT', null, 'medium', null),
  (14, 'TOMATO', null, 'medium', null),
  (14, 'ONION', null, 'easy', null),
  (14, 'SALAD', null, 'easy', null),
  (14, 'SOUP', null, 'easy', null),
  (14, 'STEAK', null, 'easy', null),
  (14, 'CHICKEN', null, 'medium', null),
  (14, 'FISH', null, 'easy', null),
  (14, 'CAKE', null, 'easy', null),
  (14, 'COOKIE', null, 'medium', null),
  (14, 'CHOCOLATE', null, 'hard', null),
  (14, 'ICECREAM', null, 'medium', null),
  (14, 'JAM', null, 'easy', null),
  (14, 'PEPPER', null, 'medium', null),
  (14, 'VINEGAR', null, 'medium', null),
  (14, 'MEATBALL', null, 'medium', null),
  (14, 'POPCORN', null, 'medium', null),
  (15, 'ITALY', null, 'easy', null),
  (15, 'FRANCE', null, 'medium', null),
  (15, 'SPAIN', null, 'easy', null),
  (15, 'PORTUGAL', null, 'medium', null),
  (15, 'GERMANY', null, 'medium', null),
  (15, 'AUSTRIA', null, 'medium', null),
  (15, 'SWITZERLAND', null, 'hard', null),
  (15, 'HOLLAND', null, 'medium', null),
  (15, 'BELGIUM', null, 'medium', null),
  (15, 'IRELAND', null, 'medium', null),
  (15, 'DENMARK', null, 'medium', null),
  (15, 'SWEDEN', null, 'medium', null),
  (15, 'NORWAY', null, 'medium', null),
  (15, 'FINLAND', null, 'medium', null),
  (15, 'POLAND', null, 'medium', null),
  (15, 'RUSSIA', null, 'medium', null),
  (15, 'GREECE', null, 'medium', null),
  (15, 'TURKEY', null, 'medium', null),
  (15, 'EGYPT', null, 'easy', null),
  (15, 'MOROCCO', null, 'medium', null),
  (15, 'AMERICA', null, 'medium', null),
  (15, 'CANADA', null, 'medium', null),
  (15, 'MEXICO', null, 'medium', null),
  (15, 'BRAZIL', null, 'medium', null),
  (15, 'CHILE', null, 'easy', null),
  (15, 'PERU', null, 'easy', null),
  (15, 'CUBA', null, 'easy', null),
  (15, 'JAPAN', null, 'easy', null),
  (15, 'CHINA', null, 'easy', null),
  (15, 'INDIA', null, 'easy', null),
  (15, 'VIETNAM', null, 'medium', null),
  (15, 'AUSTRALIA', null, 'hard', null),
  (15, 'ICELAND', null, 'medium', null),
  (15, 'ENGLAND', null, 'medium', null),
  (15, 'SCOTLAND', null, 'medium', null),
  (17, 'CORPO', null, 'easy', 'persone.corpo.0'),
  (17, 'TESTA', null, 'easy', 'persone.corpo.1'),
  (17, 'COLLO', null, 'easy', 'persone.corpo.2'),
  (17, 'TORACE', null, 'medium', 'persone.corpo.3'),
  (17, 'SENO', null, 'easy', 'persone.corpo.4'),
  (17, 'CAPEZZOLO', null, 'hard', 'persone.corpo.5'),
  (17, 'ADDOME', null, 'medium', 'persone.corpo.6'),
  (17, 'VITA', null, 'easy', 'persone.corpo.7'),
  (17, 'OMBELICO', null, 'medium', 'persone.corpo.8'),
  (17, 'FIANCO', null, 'medium', 'persone.corpo.9'),
  (17, 'AVAMBRACCIO', null, 'hard', 'persone.corpo.10'),
  (17, 'GENITALI', null, 'medium', 'persone.corpo.11'),
  (17, 'COSCIA', null, 'medium', 'persone.corpo.12'),
  (17, 'INGUINE', null, 'medium', 'persone.corpo.13'),
  (17, 'GINOCCHIO', null, 'hard', 'persone.corpo.14'),
  (17, 'GAMBA', null, 'easy', 'persone.corpo.15'),
  (17, 'STINCO', null, 'medium', 'persone.corpo.16'),
  (17, 'SCHIENA', null, 'medium', 'persone.corpo.17'),
  (17, 'NUCA', null, 'easy', 'persone.corpo.18'),
  (17, 'SPALLA', null, 'medium', 'persone.corpo.19'),
  (17, 'ASCELLA', null, 'medium', 'persone.corpo.20'),
  (17, 'BRACCIO', null, 'medium', 'persone.corpo.21'),
  (17, 'GOMITO', null, 'medium', 'persone.corpo.22'),
  (17, 'NATICA', null, 'medium', 'persone.corpo.23'),
  (17, 'MANO', null, 'easy', 'persone.corpo.24'),
  (17, 'POLPACCIO', null, 'hard', 'persone.corpo.25'),
  (17, 'CAVIGLIA', null, 'medium', 'persone.corpo.26'),
  (17, 'TALLONE', null, 'medium', 'persone.corpo.27'),
  (17, 'PIEDE', null, 'easy', 'persone.corpo.28'),
  (17, 'UOMO', null, 'easy', 'persone.corpo.29'),
  (17, 'DONNA', null, 'easy', 'persone.corpo.30'),
  (18, 'FACCIA', null, 'medium', 'persone.viso.0'),
  (18, 'CAPELLI', null, 'medium', 'persone.viso.1'),
  (18, 'PELLE', null, 'easy', 'persone.viso.2'),
  (18, 'FRONTE', null, 'medium', 'persone.viso.3'),
  (18, 'SOPRACCIGLIO', null, 'hard', 'persone.viso.4'),
  (18, 'TEMPIA', null, 'medium', 'persone.viso.5'),
  (18, 'CIGLIO', null, 'medium', 'persone.viso.6'),
  (18, 'OCCHIO', null, 'medium', 'persone.viso.7'),
  (18, 'ORECCHIO', null, 'medium', 'persone.viso.8'),
  (18, 'GUANCIA', null, 'medium', 'persone.viso.9'),
  (18, 'NASO', null, 'easy', 'persone.viso.10'),
  (18, 'NARICE', null, 'medium', 'persone.viso.11'),
  (18, 'NEO', null, 'easy', 'persone.viso.12'),
  (18, 'BOCCA', null, 'easy', 'persone.viso.13'),
  (18, 'LABBRO', null, 'medium', 'persone.viso.14'),
  (18, 'MANDIBOLA', null, 'hard', 'persone.viso.15'),
  (18, 'MENTO', null, 'easy', 'persone.viso.16');

insert into public.words (category_id, text, display, difficulty, concept_key) values
  (18, 'RUGA', null, 'easy', 'persone.viso.17'),
  (18, 'LENTIGGINE', null, 'hard', 'persone.viso.18'),
  (18, 'FOSSETTA', null, 'medium', 'persone.viso.19'),
  (18, 'PORO', null, 'easy', 'persone.viso.20'),
  (19, 'MANO', null, 'easy', 'persone.mano.0'),
  (19, 'DITO', null, 'easy', 'persone.mano.1'),
  (19, 'POLLICE', null, 'medium', 'persone.mano.2'),
  (19, 'INDICE', null, 'medium', 'persone.mano.3'),
  (19, 'MEDIO', null, 'easy', 'persone.mano.4'),
  (19, 'ANULARE', null, 'medium', 'persone.mano.5'),
  (19, 'MIGNOLO', null, 'medium', 'persone.mano.6'),
  (19, 'PALMO', null, 'easy', 'persone.mano.7'),
  (19, 'NOCCA', null, 'easy', 'persone.mano.8'),
  (19, 'UNGHIA', null, 'medium', 'persone.mano.9'),
  (19, 'PELLICINA', null, 'hard', 'persone.mano.10'),
  (19, 'PUGNO', null, 'easy', 'persone.mano.11'),
  (19, 'POLSO', null, 'easy', 'persone.mano.12'),
  (20, 'PIEDE', null, 'easy', 'persone.piede.0'),
  (20, 'AVAMPIEDE', null, 'hard', 'persone.piede.1'),
  (20, 'DITODELPIEDE', 'DITO DEL PIEDE', 'hard', 'persone.piede.2'),
  (20, 'TALLONE', null, 'medium', 'persone.piede.3'),
  (20, 'PIANTADELPIEDE', 'PIANTA DEL PIEDE', 'hard', 'persone.piede.4'),
  (20, 'COLLODELPIEDE', 'COLLO DEL PIEDE', 'hard', 'persone.piede.5'),
  (20, 'ARCOPLANTARE', 'ARCO PLANTARE', 'hard', 'persone.piede.6'),
  (20, 'ALLUCE', null, 'medium', 'persone.piede.7'),
  (20, 'UNGHIADELPIEDE', 'UNGHIA DEL PIEDE', 'hard', 'persone.piede.8'),
  (20, 'MIGNOLODELPIEDE', 'MIGNOLO DEL PIEDE', 'hard', 'persone.piede.9'),
  (20, 'CAVIGLIA', null, 'medium', 'persone.piede.10'),
  (21, 'MUSCOLO', null, 'medium', 'persone.muscoli.0'),
  (21, 'FRONTALE', null, 'medium', 'persone.muscoli.1'),
  (21, 'PETTORALE', null, 'hard', 'persone.muscoli.2'),
  (21, 'DELTOIDE', null, 'medium', 'persone.muscoli.3'),
  (21, 'TRAPEZIO', null, 'medium', 'persone.muscoli.4'),
  (21, 'INTERCOSTALE', null, 'hard', 'persone.muscoli.5'),
  (21, 'DORSALE', null, 'medium', 'persone.muscoli.6'),
  (21, 'BICIPITE', null, 'medium', 'persone.muscoli.7'),
  (21, 'TRICIPITE', null, 'hard', 'persone.muscoli.8'),
  (21, 'ADDOMINALI', null, 'hard', 'persone.muscoli.9'),
  (21, 'GLUTEO', null, 'medium', 'persone.muscoli.10'),
  (21, 'QUADRICIPITE', null, 'hard', 'persone.muscoli.11'),
  (21, 'TENDINEDACHILLE', 'TENDINE D''ACHILLE', 'hard', 'persone.muscoli.12'),
  (22, 'SCHELETRO', null, 'hard', 'persone.scheletro.0'),
  (22, 'OSSO', null, 'easy', 'persone.scheletro.1'),
  (22, 'CRANIO', null, 'medium', 'persone.scheletro.2'),
  (22, 'CLAVICOLA', null, 'hard', 'persone.scheletro.3'),
  (22, 'SCAPOLA', null, 'medium', 'persone.scheletro.4'),
  (22, 'COLONNAVERTEBRALE', 'COLONNA VERTEBRALE', 'hard', 'persone.scheletro.5'),
  (22, 'BACINO', null, 'medium', 'persone.scheletro.6'),
  (22, 'COCCIGE', null, 'medium', 'persone.scheletro.7'),
  (22, 'OMERO', null, 'easy', 'persone.scheletro.8'),
  (22, 'RADIO', null, 'easy', 'persone.scheletro.9'),
  (22, 'ULNA', null, 'easy', 'persone.scheletro.10'),
  (22, 'FEMORE', null, 'medium', 'persone.scheletro.11'),
  (22, 'ROTULA', null, 'medium', 'persone.scheletro.12'),
  (22, 'TIBIA', null, 'easy', 'persone.scheletro.13'),
  (22, 'PERONE', null, 'medium', 'persone.scheletro.14'),
  (22, 'COSTOLA', null, 'medium', 'persone.scheletro.15'),
  (22, 'CASSATORACICA', 'CASSA TORACICA', 'hard', 'persone.scheletro.16'),
  (22, 'STERNO', null, 'medium', 'persone.scheletro.17'),
  (22, 'VERTEBRECERVICALI', 'VERTEBRE CERVICALI', 'hard', 'persone.scheletro.18'),
  (22, 'VERTEBRETORACICHE', 'VERTEBRE TORACICHE', 'hard', 'persone.scheletro.19'),
  (22, 'VERTEBRELOMBARI', 'VERTEBRE LOMBARI', 'hard', 'persone.scheletro.20'),
  (22, 'ARTICOLAZIONE', null, 'hard', 'persone.scheletro.21'),
  (22, 'LEGAMENTO', null, 'hard', 'persone.scheletro.22'),
  (22, 'TENDINE', null, 'medium', 'persone.scheletro.23'),
  (22, 'METACARPO', null, 'hard', 'persone.scheletro.24'),
  (22, 'METATARSO', null, 'hard', 'persone.scheletro.25'),
  (22, 'CARTILAGINE', null, 'hard', 'persone.scheletro.26'),
  (23, 'CUORE', null, 'easy', 'persone.organi-interni.0'),
  (23, 'POLMONE', null, 'medium', 'persone.organi-interni.1'),
  (23, 'FEGATO', null, 'medium', 'persone.organi-interni.2'),
  (23, 'STOMACO', null, 'medium', 'persone.organi-interni.3'),
  (23, 'RENE', null, 'easy', 'persone.organi-interni.4'),
  (23, 'MILZA', null, 'easy', 'persone.organi-interni.5'),
  (23, 'PANCREAS', null, 'medium', 'persone.organi-interni.6'),
  (23, 'TIROIDE', null, 'medium', 'persone.organi-interni.7'),
  (23, 'TRACHEA', null, 'medium', 'persone.organi-interni.8'),
  (23, 'DUODENO', null, 'medium', 'persone.organi-interni.9'),
  (23, 'INTESTINOTENUE', 'INTESTINO TENUE', 'hard', 'persone.organi-interni.10'),
  (23, 'INTESTINOCRASSO', 'INTESTINO CRASSO', 'hard', 'persone.organi-interni.11'),
  (23, 'APPENDICE', null, 'hard', 'persone.organi-interni.12'),
  (24, 'CERVELLO', null, 'medium', 'persone.testa.0'),
  (24, 'SENOPARANASALE', 'SENO PARANASALE', 'hard', 'persone.testa.1'),
  (24, 'PALATO', null, 'medium', 'persone.testa.2'),
  (24, 'FARINGE', null, 'medium', 'persone.testa.3'),
  (24, 'LINGUA', null, 'medium', 'persone.testa.4'),
  (24, 'EPIGLOTTIDE', null, 'hard', 'persone.testa.5'),
  (24, 'LARINGE', null, 'medium', 'persone.testa.6'),
  (24, 'ESOFAGO', null, 'medium', 'persone.testa.7'),
  (24, 'POMODADAMO', 'POMO D''ADAMO', 'hard', 'persone.testa.8'),
  (24, 'CORDEVOCALI', 'CORDE VOCALI', 'hard', 'persone.testa.9'),
  (24, 'GOLA', null, 'easy', 'persone.testa.10'),
  (25, 'DIAFRAMMA', null, 'hard', 'persone.sistemi-corporei.0'),
  (25, 'VENA', null, 'easy', 'persone.sistemi-corporei.1'),
  (25, 'ARTERIA', null, 'medium', 'persone.sistemi-corporei.2'),
  (25, 'GHIANDOLA', null, 'hard', 'persone.sistemi-corporei.3'),
  (25, 'NERVO', null, 'easy', 'persone.sistemi-corporei.4'),
  (25, 'RESPIRATORIO', null, 'hard', 'persone.sistemi-corporei.5'),
  (25, 'DIGESTIVO', null, 'hard', 'persone.sistemi-corporei.6'),
  (25, 'CARDIOVASCOLARE', null, 'hard', 'persone.sistemi-corporei.7');

insert into public.words (category_id, text, display, difficulty, concept_key) values
  (25, 'LINFATICO', null, 'hard', 'persone.sistemi-corporei.8'),
  (25, 'URINARIO', null, 'medium', 'persone.sistemi-corporei.9'),
  (25, 'ENDOCRINO', null, 'hard', 'persone.sistemi-corporei.10'),
  (25, 'NERVOSO', null, 'medium', 'persone.sistemi-corporei.11'),
  (25, 'RIPRODUTTIVO', null, 'hard', 'persone.sistemi-corporei.12'),
  (26, 'OVAIA', null, 'easy', 'persone.organi-riproduttivi.0'),
  (26, 'FOLLICOLO', null, 'hard', 'persone.organi-riproduttivi.1'),
  (26, 'TUBODIFALLOPPIO', 'TUBO DI FALLOPPIO', 'hard', 'persone.organi-riproduttivi.2'),
  (26, 'UTERO', null, 'easy', 'persone.organi-riproduttivi.3'),
  (26, 'COLLODELLUTERO', 'COLLO DELL''UTERO', 'hard', 'persone.organi-riproduttivi.4'),
  (26, 'VAGINA', null, 'medium', 'persone.organi-riproduttivi.5'),
  (26, 'CLITORIDE', null, 'hard', 'persone.organi-riproduttivi.6'),
  (26, 'LABBRA', null, 'medium', 'persone.organi-riproduttivi.7'),
  (26, 'VESCICA', null, 'medium', 'persone.organi-riproduttivi.8'),
  (26, 'URETRA', null, 'medium', 'persone.organi-riproduttivi.9'),
  (26, 'PENE', null, 'easy', 'persone.organi-riproduttivi.10'),
  (26, 'TESTICOLO', null, 'hard', 'persone.organi-riproduttivi.11'),
  (26, 'SCROTO', null, 'medium', 'persone.organi-riproduttivi.12'),
  (26, 'PREPUZIO', null, 'medium', 'persone.organi-riproduttivi.13'),
  (26, 'PROSTATA', null, 'medium', 'persone.organi-riproduttivi.14'),
  (26, 'VESCICOLASEMINALE', 'VESCICOLA SEMINALE', 'hard', 'persone.organi-riproduttivi.15'),
  (26, 'DOTTODEFERENTE', 'DOTTO DEFERENTE', 'hard', 'persone.organi-riproduttivi.16'),
  (26, 'DOTTOEIACULATORE', 'DOTTO EIACULATORE', 'hard', 'persone.organi-riproduttivi.17'),
  (26, 'URETERE', null, 'medium', 'persone.organi-riproduttivi.18'),
  (26, 'RETTO', null, 'easy', 'persone.organi-riproduttivi.19'),
  (26, 'ORMONE', null, 'medium', 'persone.organi-riproduttivi.20'),
  (26, 'SPERMA', null, 'medium', 'persone.organi-riproduttivi.21'),
  (26, 'OVULO', null, 'easy', 'persone.organi-riproduttivi.22'),
  (26, 'MESTRUAZIONE', null, 'hard', 'persone.organi-riproduttivi.23'),
  (26, 'OVULAZIONE', null, 'hard', 'persone.organi-riproduttivi.24'),
  (26, 'FECONDO', null, 'medium', 'persone.organi-riproduttivi.25'),
  (26, 'STERILE', null, 'medium', 'persone.organi-riproduttivi.26'),
  (26, 'IMPOTENTE', null, 'hard', 'persone.organi-riproduttivi.27'),
  (26, 'CONCEPIRE', null, 'hard', 'persone.organi-riproduttivi.28'),
  (26, 'FECONDAZIONE', null, 'hard', 'persone.organi-riproduttivi.29'),
  (26, 'COITO', null, 'easy', 'persone.organi-riproduttivi.30'),
  (26, 'MASCHILE', null, 'medium', 'persone.organi-riproduttivi.31'),
  (26, 'FEMMINILE', null, 'hard', 'persone.organi-riproduttivi.32'),
  (27, 'CONTRACCEZIONE', null, 'hard', 'persone.contraccezione.0'),
  (27, 'PRESERVATIVO', null, 'hard', 'persone.contraccezione.1'),
  (27, 'PILLOLA', null, 'medium', 'persone.contraccezione.2'),
  (27, 'DIAFRAMMA', null, 'hard', 'persone.contraccezione.3'),
  (27, 'PESSARIO', null, 'medium', 'persone.contraccezione.4'),
  (27, 'CAPPUCCIOCERVICALE', 'CAPPUCCIO CERVICALE', 'hard', 'persone.contraccezione.5'),
  (27, 'SPIRALE', null, 'medium', 'persone.contraccezione.6'),
  (29, 'BODY', null, 'easy', 'persone.corpo.0'),
  (29, 'HEAD', null, 'easy', 'persone.corpo.1'),
  (29, 'NECK', null, 'easy', 'persone.corpo.2'),
  (29, 'CHEST', null, 'easy', 'persone.corpo.3'),
  (29, 'BREAST', null, 'medium', 'persone.corpo.4'),
  (29, 'NIPPLE', null, 'medium', 'persone.corpo.5'),
  (29, 'ABDOMEN', null, 'medium', 'persone.corpo.6'),
  (29, 'WAIST', null, 'easy', 'persone.corpo.7'),
  (29, 'NAVEL', null, 'easy', 'persone.corpo.8'),
  (29, 'HIP', null, 'easy', 'persone.corpo.9'),
  (29, 'FOREARM', null, 'medium', 'persone.corpo.10'),
  (29, 'GENITALS', null, 'medium', 'persone.corpo.11'),
  (29, 'THIGH', null, 'easy', 'persone.corpo.12'),
  (29, 'GROIN', null, 'easy', 'persone.corpo.13'),
  (29, 'KNEE', null, 'easy', 'persone.corpo.14'),
  (29, 'LEG', null, 'easy', 'persone.corpo.15'),
  (29, 'SHIN', null, 'easy', 'persone.corpo.16'),
  (29, 'BACK', null, 'easy', 'persone.corpo.17'),
  (29, 'NAPE', null, 'easy', 'persone.corpo.18'),
  (29, 'SHOULDER', null, 'medium', 'persone.corpo.19'),
  (29, 'ARMPIT', null, 'medium', 'persone.corpo.20'),
  (29, 'ARM', null, 'easy', 'persone.corpo.21'),
  (29, 'ELBOW', null, 'easy', 'persone.corpo.22'),
  (29, 'BUTTOCK', null, 'medium', 'persone.corpo.23'),
  (29, 'HAND', null, 'easy', 'persone.corpo.24'),
  (29, 'CALF', null, 'easy', 'persone.corpo.25'),
  (29, 'ANKLE', null, 'easy', 'persone.corpo.26'),
  (29, 'HEEL', null, 'easy', 'persone.corpo.27'),
  (29, 'FOOT', null, 'easy', 'persone.corpo.28'),
  (29, 'MALE', null, 'easy', 'persone.corpo.29'),
  (29, 'FEMALE', null, 'medium', 'persone.corpo.30'),
  (30, 'FACE', null, 'easy', 'persone.viso.0'),
  (30, 'HAIR', null, 'easy', 'persone.viso.1'),
  (30, 'SKIN', null, 'easy', 'persone.viso.2'),
  (30, 'FOREHEAD', null, 'medium', 'persone.viso.3'),
  (30, 'EYEBROW', null, 'medium', 'persone.viso.4'),
  (30, 'TEMPLE', null, 'medium', 'persone.viso.5'),
  (30, 'EYELASH', null, 'medium', 'persone.viso.6'),
  (30, 'EYE', null, 'easy', 'persone.viso.7'),
  (30, 'EAR', null, 'easy', 'persone.viso.8'),
  (30, 'CHEEK', null, 'easy', 'persone.viso.9'),
  (30, 'NOSE', null, 'easy', 'persone.viso.10'),
  (30, 'NOSTRIL', null, 'medium', 'persone.viso.11'),
  (30, 'MOLE', null, 'easy', 'persone.viso.12'),
  (30, 'MOUTH', null, 'easy', 'persone.viso.13'),
  (30, 'LIP', null, 'easy', 'persone.viso.14'),
  (30, 'JAW', null, 'easy', 'persone.viso.15'),
  (30, 'CHIN', null, 'easy', 'persone.viso.16'),
  (30, 'WRINKLE', null, 'medium', 'persone.viso.17'),
  (30, 'FRECKLE', null, 'medium', 'persone.viso.18'),
  (30, 'DIMPLE', null, 'medium', 'persone.viso.19'),
  (30, 'PORE', null, 'easy', 'persone.viso.20'),
  (31, 'HAND', null, 'easy', 'persone.mano.0'),
  (31, 'FINGER', null, 'medium', 'persone.mano.1'),
  (31, 'THUMB', null, 'easy', 'persone.mano.2');

insert into public.words (category_id, text, display, difficulty, concept_key) values
  (31, 'INDEXFINGER', 'INDEX FINGER', 'hard', 'persone.mano.3'),
  (31, 'MIDDLEFINGER', 'MIDDLE FINGER', 'hard', 'persone.mano.4'),
  (31, 'RINGFINGER', 'RING FINGER', 'hard', 'persone.mano.5'),
  (31, 'LITTLEFINGER', 'LITTLE FINGER', 'hard', 'persone.mano.6'),
  (31, 'PALM', null, 'easy', 'persone.mano.7'),
  (31, 'KNUCKLE', null, 'medium', 'persone.mano.8'),
  (31, 'NAIL', null, 'easy', 'persone.mano.9'),
  (31, 'CUTICLE', null, 'medium', 'persone.mano.10'),
  (31, 'FIST', null, 'easy', 'persone.mano.11'),
  (31, 'WRIST', null, 'easy', 'persone.mano.12'),
  (32, 'FOOT', null, 'easy', 'persone.piede.0'),
  (32, 'BALLOFFOOT', 'BALL OF FOOT', 'hard', 'persone.piede.1'),
  (32, 'TOE', null, 'easy', 'persone.piede.2'),
  (32, 'HEEL', null, 'easy', 'persone.piede.3'),
  (32, 'SOLE', null, 'easy', 'persone.piede.4'),
  (32, 'INSTEP', null, 'medium', 'persone.piede.5'),
  (32, 'ARCH', null, 'easy', 'persone.piede.6'),
  (32, 'BIGTOE', 'BIG TOE', 'medium', 'persone.piede.7'),
  (32, 'TOENAIL', null, 'medium', 'persone.piede.8'),
  (32, 'LITTLETOE', 'LITTLE TOE', 'hard', 'persone.piede.9'),
  (32, 'ANKLE', null, 'easy', 'persone.piede.10'),
  (33, 'MUSCLE', null, 'medium', 'persone.muscoli.0'),
  (33, 'FRONTAL', null, 'medium', 'persone.muscoli.1'),
  (33, 'PECTORAL', null, 'medium', 'persone.muscoli.2'),
  (33, 'DELTOID', null, 'medium', 'persone.muscoli.3'),
  (33, 'TRAPEZIUS', null, 'hard', 'persone.muscoli.4'),
  (33, 'INTERCOSTAL', null, 'hard', 'persone.muscoli.5'),
  (33, 'LATISSIMUSDORSI', 'LATISSIMUS DORSI', 'hard', 'persone.muscoli.6'),
  (33, 'BICEPS', null, 'medium', 'persone.muscoli.7'),
  (33, 'TRICEPS', null, 'medium', 'persone.muscoli.8'),
  (33, 'ABDOMINALS', null, 'hard', 'persone.muscoli.9'),
  (33, 'GLUTEUS', null, 'medium', 'persone.muscoli.10'),
  (33, 'QUADRICEPS', null, 'hard', 'persone.muscoli.11'),
  (33, 'ACHILLESTENDON', 'ACHILLES TENDON', 'hard', 'persone.muscoli.12'),
  (34, 'SKELETON', null, 'medium', 'persone.scheletro.0'),
  (34, 'BONE', null, 'easy', 'persone.scheletro.1'),
  (34, 'SKULL', null, 'easy', 'persone.scheletro.2'),
  (34, 'COLLARBONE', 'COLLAR BONE', 'hard', 'persone.scheletro.3'),
  (34, 'SHOULDERBLADE', 'SHOULDER BLADE', 'hard', 'persone.scheletro.4'),
  (34, 'SPINE', null, 'easy', 'persone.scheletro.5'),
  (34, 'PELVIS', null, 'medium', 'persone.scheletro.6'),
  (34, 'TAILBONE', null, 'medium', 'persone.scheletro.7'),
  (34, 'HUMERUS', null, 'medium', 'persone.scheletro.8'),
  (34, 'RADIUS', null, 'medium', 'persone.scheletro.9'),
  (34, 'ULNA', null, 'easy', 'persone.scheletro.10'),
  (34, 'FEMUR', null, 'easy', 'persone.scheletro.11'),
  (34, 'KNEECAP', null, 'medium', 'persone.scheletro.12'),
  (34, 'TIBIA', null, 'easy', 'persone.scheletro.13'),
  (34, 'FIBULA', null, 'medium', 'persone.scheletro.14'),
  (34, 'RIB', null, 'easy', 'persone.scheletro.15'),
  (34, 'RIBCAGE', 'RIB CAGE', 'medium', 'persone.scheletro.16'),
  (34, 'STERNUM', null, 'medium', 'persone.scheletro.17'),
  (34, 'CERVICALVERTEBRAE', 'CERVICAL VERTEBRAE', 'hard', 'persone.scheletro.18'),
  (34, 'THORACICVERTEBRAE', 'THORACIC VERTEBRAE', 'hard', 'persone.scheletro.19'),
  (34, 'LUMBARVERTEBRAE', 'LUMBAR VERTEBRAE', 'hard', 'persone.scheletro.20'),
  (34, 'JOINT', null, 'easy', 'persone.scheletro.21'),
  (34, 'LIGAMENT', null, 'medium', 'persone.scheletro.22'),
  (34, 'TENDON', null, 'medium', 'persone.scheletro.23'),
  (34, 'METACARPAL', null, 'hard', 'persone.scheletro.24'),
  (34, 'METATARSAL', null, 'hard', 'persone.scheletro.25'),
  (34, 'CARTILAGE', null, 'hard', 'persone.scheletro.26'),
  (35, 'HEART', null, 'easy', 'persone.organi-interni.0'),
  (35, 'LUNG', null, 'easy', 'persone.organi-interni.1'),
  (35, 'LIVER', null, 'easy', 'persone.organi-interni.2'),
  (35, 'STOMACH', null, 'medium', 'persone.organi-interni.3'),
  (35, 'KIDNEY', null, 'medium', 'persone.organi-interni.4'),
  (35, 'SPLEEN', null, 'medium', 'persone.organi-interni.5'),
  (35, 'PANCREAS', null, 'medium', 'persone.organi-interni.6'),
  (35, 'THYROIDGLAND', 'THYROID GLAND', 'hard', 'persone.organi-interni.7'),
  (35, 'WINDPIPE', null, 'medium', 'persone.organi-interni.8'),
  (35, 'DUODENUM', null, 'medium', 'persone.organi-interni.9'),
  (35, 'SMALLINTESTINE', 'SMALL INTESTINE', 'hard', 'persone.organi-interni.10'),
  (35, 'LARGEINTESTINE', 'LARGE INTESTINE', 'hard', 'persone.organi-interni.11'),
  (35, 'APPENDIX', null, 'medium', 'persone.organi-interni.12'),
  (36, 'BRAIN', null, 'easy', 'persone.testa.0'),
  (36, 'SINUS', null, 'easy', 'persone.testa.1'),
  (36, 'PALATE', null, 'medium', 'persone.testa.2'),
  (36, 'PHARYNX', null, 'medium', 'persone.testa.3'),
  (36, 'TONGUE', null, 'medium', 'persone.testa.4'),
  (36, 'EPIGLOTTIS', null, 'hard', 'persone.testa.5'),
  (36, 'LARYNX', null, 'medium', 'persone.testa.6'),
  (36, 'ESOPHAGUS', null, 'hard', 'persone.testa.7'),
  (36, 'ADAMSAPPLE', 'ADAM''S APPLE', 'hard', 'persone.testa.8'),
  (36, 'VOCALCORDS', 'VOCAL CORDS', 'hard', 'persone.testa.9'),
  (36, 'THROAT', null, 'medium', 'persone.testa.10'),
  (37, 'DIAPHRAGM', null, 'hard', 'persone.sistemi-corporei.0'),
  (37, 'VEIN', null, 'easy', 'persone.sistemi-corporei.1'),
  (37, 'ARTERY', null, 'medium', 'persone.sistemi-corporei.2'),
  (37, 'GLAND', null, 'easy', 'persone.sistemi-corporei.3'),
  (37, 'NERVE', null, 'easy', 'persone.sistemi-corporei.4'),
  (37, 'RESPIRATORY', null, 'hard', 'persone.sistemi-corporei.5'),
  (37, 'DIGESTIVE', null, 'hard', 'persone.sistemi-corporei.6'),
  (37, 'CARDIOVASCULAR', null, 'hard', 'persone.sistemi-corporei.7'),
  (37, 'LYMPHATIC', null, 'hard', 'persone.sistemi-corporei.8'),
  (37, 'URINARY', null, 'medium', 'persone.sistemi-corporei.9'),
  (37, 'ENDOCRINE', null, 'hard', 'persone.sistemi-corporei.10'),
  (37, 'NERVOUS', null, 'medium', 'persone.sistemi-corporei.11'),
  (37, 'REPRODUCTIVE', null, 'hard', 'persone.sistemi-corporei.12'),
  (38, 'OVARY', null, 'easy', 'persone.organi-riproduttivi.0'),
  (38, 'FOLLICLE', null, 'medium', 'persone.organi-riproduttivi.1');

insert into public.words (category_id, text, display, difficulty, concept_key) values
  (38, 'FALLOPIANTUBE', 'FALLOPIAN TUBE', 'hard', 'persone.organi-riproduttivi.2'),
  (38, 'UTERUS', null, 'medium', 'persone.organi-riproduttivi.3'),
  (38, 'CERVIX', null, 'medium', 'persone.organi-riproduttivi.4'),
  (38, 'VAGINA', null, 'medium', 'persone.organi-riproduttivi.5'),
  (38, 'CLITORIS', null, 'medium', 'persone.organi-riproduttivi.6'),
  (38, 'LABIA', null, 'easy', 'persone.organi-riproduttivi.7'),
  (38, 'BLADDER', null, 'medium', 'persone.organi-riproduttivi.8'),
  (38, 'URETHRA', null, 'medium', 'persone.organi-riproduttivi.9'),
  (38, 'PENIS', null, 'easy', 'persone.organi-riproduttivi.10'),
  (38, 'TESTICLE', null, 'medium', 'persone.organi-riproduttivi.11'),
  (38, 'SCROTUM', null, 'medium', 'persone.organi-riproduttivi.12'),
  (38, 'FORESKIN', null, 'medium', 'persone.organi-riproduttivi.13'),
  (38, 'PROSTATE', null, 'medium', 'persone.organi-riproduttivi.14'),
  (38, 'SEMINALVESICLE', 'SEMINAL VESICLE', 'hard', 'persone.organi-riproduttivi.15'),
  (38, 'VASDEFERENS', 'VAS DEFERENS', 'hard', 'persone.organi-riproduttivi.16'),
  (38, 'EJACULATORYDUCT', 'EJACULATORY DUCT', 'hard', 'persone.organi-riproduttivi.17'),
  (38, 'URETER', null, 'medium', 'persone.organi-riproduttivi.18'),
  (38, 'RECTUM', null, 'medium', 'persone.organi-riproduttivi.19'),
  (38, 'HORMONE', null, 'medium', 'persone.organi-riproduttivi.20'),
  (38, 'SPERM', null, 'easy', 'persone.organi-riproduttivi.21'),
  (38, 'EGG', null, 'easy', 'persone.organi-riproduttivi.22'),
  (38, 'MENSTRUATION', null, 'hard', 'persone.organi-riproduttivi.23'),
  (38, 'OVULATION', null, 'hard', 'persone.organi-riproduttivi.24'),
  (38, 'FERTILE', null, 'medium', 'persone.organi-riproduttivi.25'),
  (38, 'INFERTILE', null, 'hard', 'persone.organi-riproduttivi.26'),
  (38, 'IMPOTENT', null, 'medium', 'persone.organi-riproduttivi.27'),
  (38, 'CONCEIVE', null, 'medium', 'persone.organi-riproduttivi.28'),
  (38, 'FERTILIZATION', null, 'hard', 'persone.organi-riproduttivi.29'),
  (38, 'INTERCOURSE', null, 'hard', 'persone.organi-riproduttivi.30'),
  (38, 'MALE', null, 'easy', 'persone.organi-riproduttivi.31'),
  (38, 'FEMALE', null, 'medium', 'persone.organi-riproduttivi.32'),
  (39, 'CONTRACEPTION', null, 'hard', 'persone.contraccezione.0'),
  (39, 'CONDOM', null, 'medium', 'persone.contraccezione.1'),
  (39, 'PILL', null, 'easy', 'persone.contraccezione.2'),
  (39, 'DIAPHRAGM', null, 'hard', 'persone.contraccezione.3'),
  (39, 'CAP', null, 'easy', 'persone.contraccezione.4'),
  (39, 'CERVICALCAP', 'CERVICAL CAP', 'hard', 'persone.contraccezione.5'),
  (39, 'IUD', null, 'easy', 'persone.contraccezione.6'),
  (41, 'CORPS', null, 'easy', 'persone.corpo.0'),
  (41, 'TÊTE', null, 'easy', 'persone.corpo.1'),
  (41, 'COU', null, 'easy', 'persone.corpo.2'),
  (41, 'POITRINE', null, 'medium', 'persone.corpo.3'),
  (41, 'SEIN', null, 'easy', 'persone.corpo.4'),
  (41, 'MAMELON', null, 'medium', 'persone.corpo.5'),
  (41, 'VENTRE', null, 'medium', 'persone.corpo.6'),
  (41, 'TAILLE', null, 'medium', 'persone.corpo.7'),
  (41, 'NOMBRIL', null, 'medium', 'persone.corpo.8'),
  (41, 'HANCHE', null, 'medium', 'persone.corpo.9'),
  (41, 'AVANTBRAS', 'AVANT-BRAS', 'hard', 'persone.corpo.10'),
  (41, 'ORGANESGÉNITAUX', 'ORGANES GÉNITAUX', 'hard', 'persone.corpo.11'),
  (41, 'CUISSE', null, 'medium', 'persone.corpo.12'),
  (41, 'AINE', null, 'easy', 'persone.corpo.13'),
  (41, 'GENOU', null, 'easy', 'persone.corpo.14'),
  (41, 'JAMBE', null, 'easy', 'persone.corpo.15'),
  (41, 'TIBIA', null, 'easy', 'persone.corpo.16'),
  (41, 'DOS', null, 'easy', 'persone.corpo.17'),
  (41, 'NUQUE', null, 'easy', 'persone.corpo.18'),
  (41, 'ÉPAULE', null, 'medium', 'persone.corpo.19'),
  (41, 'AISSELLE', null, 'medium', 'persone.corpo.20'),
  (41, 'BRAS', null, 'easy', 'persone.corpo.21'),
  (41, 'COUDE', null, 'easy', 'persone.corpo.22'),
  (41, 'FESSE', null, 'easy', 'persone.corpo.23'),
  (41, 'MAIN', null, 'easy', 'persone.corpo.24'),
  (41, 'MOLLET', null, 'medium', 'persone.corpo.25'),
  (41, 'CHEVILLE', null, 'medium', 'persone.corpo.26'),
  (41, 'TALON', null, 'easy', 'persone.corpo.27'),
  (41, 'PIED', null, 'easy', 'persone.corpo.28'),
  (41, 'HOMME', null, 'easy', 'persone.corpo.29'),
  (41, 'FEMME', null, 'easy', 'persone.corpo.30'),
  (42, 'VISAGE', null, 'medium', 'persone.viso.0'),
  (42, 'CHEVEUX', null, 'medium', 'persone.viso.1'),
  (42, 'PEAU', null, 'easy', 'persone.viso.2'),
  (42, 'FRONT', null, 'easy', 'persone.viso.3'),
  (42, 'SOURCIL', null, 'medium', 'persone.viso.4'),
  (42, 'TEMPE', null, 'easy', 'persone.viso.5'),
  (42, 'CIL', null, 'easy', 'persone.viso.6'),
  (42, 'OEIL', null, 'easy', 'persone.viso.7'),
  (42, 'OREILLE', null, 'medium', 'persone.viso.8'),
  (42, 'JOUE', null, 'easy', 'persone.viso.9'),
  (42, 'NEZ', null, 'easy', 'persone.viso.10'),
  (42, 'NARINE', null, 'medium', 'persone.viso.11'),
  (42, 'GRAINDEBEAUTÉ', 'GRAIN DE BEAUTÉ', 'hard', 'persone.viso.12'),
  (42, 'BOUCHE', null, 'medium', 'persone.viso.13'),
  (42, 'LÈVRE', null, 'easy', 'persone.viso.14'),
  (42, 'MÂCHOIRE', null, 'medium', 'persone.viso.15'),
  (42, 'MENTON', null, 'medium', 'persone.viso.16'),
  (42, 'RIDE', null, 'easy', 'persone.viso.17'),
  (42, 'TACHEDEROUSSEUR', 'TACHE DE ROUSSEUR', 'hard', 'persone.viso.18'),
  (42, 'FOSSETTE', null, 'medium', 'persone.viso.19'),
  (42, 'PORE', null, 'easy', 'persone.viso.20'),
  (43, 'MAIN', null, 'easy', 'persone.mano.0'),
  (43, 'DOIGT', null, 'easy', 'persone.mano.1'),
  (43, 'POUCE', null, 'easy', 'persone.mano.2'),
  (43, 'INDEX', null, 'easy', 'persone.mano.3'),
  (43, 'MAJEUR', null, 'medium', 'persone.mano.4'),
  (43, 'ANNULAIRE', null, 'hard', 'persone.mano.5'),
  (43, 'AURICULAIRE', null, 'hard', 'persone.mano.6'),
  (43, 'PAUME', null, 'easy', 'persone.mano.7'),
  (43, 'JOINTURE', null, 'medium', 'persone.mano.8'),
  (43, 'ONGLE', null, 'easy', 'persone.mano.9');

insert into public.words (category_id, text, display, difficulty, concept_key) values
  (43, 'CUTICULE', null, 'medium', 'persone.mano.10'),
  (43, 'POING', null, 'easy', 'persone.mano.11'),
  (43, 'POIGNET', null, 'medium', 'persone.mano.12'),
  (44, 'PIED', null, 'easy', 'persone.piede.0'),
  (44, 'AVANTPIED', 'AVANT-PIED', 'hard', 'persone.piede.1'),
  (44, 'ORTEIL', null, 'medium', 'persone.piede.2'),
  (44, 'TALON', null, 'easy', 'persone.piede.3'),
  (44, 'PLANTEDUPIED', 'PLANTE DU PIED', 'hard', 'persone.piede.4'),
  (44, 'COUDEPIED', 'COU-DE-PIED', 'hard', 'persone.piede.5'),
  (44, 'CAMBRURE', null, 'medium', 'persone.piede.6'),
  (44, 'GROSORTEIL', 'GROS ORTEIL', 'hard', 'persone.piede.7'),
  (44, 'ONGLEDUPIED', 'ONGLE DU PIED', 'hard', 'persone.piede.8'),
  (44, 'PETITORTEIL', 'PETIT ORTEIL', 'hard', 'persone.piede.9'),
  (44, 'CHEVILLE', null, 'medium', 'persone.piede.10'),
  (45, 'MUSCLE', null, 'medium', 'persone.muscoli.0'),
  (45, 'FRONTAL', null, 'medium', 'persone.muscoli.1'),
  (45, 'PECTORAL', null, 'medium', 'persone.muscoli.2'),
  (45, 'DELTOÏDE', null, 'medium', 'persone.muscoli.3'),
  (45, 'TRAPÈZE', null, 'medium', 'persone.muscoli.4'),
  (45, 'INTERCOSTAL', null, 'hard', 'persone.muscoli.5'),
  (45, 'DORSAL', null, 'medium', 'persone.muscoli.6'),
  (45, 'BICEPS', null, 'medium', 'persone.muscoli.7'),
  (45, 'TRICEPS', null, 'medium', 'persone.muscoli.8'),
  (45, 'ABDOMINAUX', null, 'hard', 'persone.muscoli.9'),
  (45, 'FESSIER', null, 'medium', 'persone.muscoli.10'),
  (45, 'QUADRICEPS', null, 'hard', 'persone.muscoli.11'),
  (45, 'TENDONDACHILLE', 'TENDON D''ACHILLE', 'hard', 'persone.muscoli.12'),
  (46, 'SQUELETTE', null, 'hard', 'persone.scheletro.0'),
  (46, 'OS', null, 'easy', 'persone.scheletro.1'),
  (46, 'CRÂNE', null, 'easy', 'persone.scheletro.2'),
  (46, 'CLAVICULE', null, 'hard', 'persone.scheletro.3'),
  (46, 'OMOPLATE', null, 'medium', 'persone.scheletro.4'),
  (46, 'COLONNEVERTÉBRALE', 'COLONNE VERTÉBRALE', 'hard', 'persone.scheletro.5'),
  (46, 'BASSIN', null, 'medium', 'persone.scheletro.6'),
  (46, 'COCCYX', null, 'medium', 'persone.scheletro.7'),
  (46, 'HUMÉRUS', null, 'medium', 'persone.scheletro.8'),
  (46, 'RADIUS', null, 'medium', 'persone.scheletro.9'),
  (46, 'CUBITUS', null, 'medium', 'persone.scheletro.10'),
  (46, 'FÉMUR', null, 'easy', 'persone.scheletro.11'),
  (46, 'ROTULE', null, 'medium', 'persone.scheletro.12'),
  (46, 'TIBIA', null, 'easy', 'persone.scheletro.13'),
  (46, 'PÉRONÉ', null, 'medium', 'persone.scheletro.14'),
  (46, 'CÔTE', null, 'easy', 'persone.scheletro.15'),
  (46, 'CAGETHORACIQUE', 'CAGE THORACIQUE', 'hard', 'persone.scheletro.16'),
  (46, 'STERNUM', null, 'medium', 'persone.scheletro.17'),
  (46, 'VERTÈBRESCERVICALES', 'VERTÈBRES CERVICALES', 'hard', 'persone.scheletro.18'),
  (46, 'VERTÈBRESTHORACIQUES', 'VERTÈBRES THORACIQUES', 'hard', 'persone.scheletro.19'),
  (46, 'VERTÈBRESLOMBAIRES', 'VERTÈBRES LOMBAIRES', 'hard', 'persone.scheletro.20'),
  (46, 'ARTICULATION', null, 'hard', 'persone.scheletro.21'),
  (46, 'LIGAMENT', null, 'medium', 'persone.scheletro.22'),
  (46, 'TENDON', null, 'medium', 'persone.scheletro.23'),
  (46, 'MÉTACARPIEN', null, 'hard', 'persone.scheletro.24'),
  (46, 'MÉTATARSIEN', null, 'hard', 'persone.scheletro.25'),
  (46, 'CARTILAGE', null, 'hard', 'persone.scheletro.26'),
  (47, 'COEUR', null, 'easy', 'persone.organi-interni.0'),
  (47, 'POUMON', null, 'medium', 'persone.organi-interni.1'),
  (47, 'FOIE', null, 'easy', 'persone.organi-interni.2'),
  (47, 'ESTOMAC', null, 'medium', 'persone.organi-interni.3'),
  (47, 'REIN', null, 'easy', 'persone.organi-interni.4'),
  (47, 'RATE', null, 'easy', 'persone.organi-interni.5'),
  (47, 'PANCRÉAS', null, 'medium', 'persone.organi-interni.6'),
  (47, 'THYROÏDE', null, 'medium', 'persone.organi-interni.7'),
  (47, 'TRACHÉE', null, 'medium', 'persone.organi-interni.8'),
  (47, 'DUODÉNUM', null, 'medium', 'persone.organi-interni.9'),
  (47, 'INTESTINGRÊLE', 'INTESTIN GRÊLE', 'hard', 'persone.organi-interni.10'),
  (47, 'GROSINTESTIN', 'GROS INTESTIN', 'hard', 'persone.organi-interni.11'),
  (47, 'APPENDICE', null, 'hard', 'persone.organi-interni.12'),
  (48, 'CERVEAU', null, 'medium', 'persone.testa.0'),
  (48, 'SINUS', null, 'easy', 'persone.testa.1'),
  (48, 'PALAIS', null, 'medium', 'persone.testa.2'),
  (48, 'PHARYNX', null, 'medium', 'persone.testa.3'),
  (48, 'LANGUE', null, 'medium', 'persone.testa.4'),
  (48, 'ÉPIGLOTTE', null, 'hard', 'persone.testa.5'),
  (48, 'LARYNX', null, 'medium', 'persone.testa.6'),
  (48, 'OESOPHAGE', null, 'hard', 'persone.testa.7'),
  (48, 'POMMEDADAM', 'POMME D''ADAM', 'hard', 'persone.testa.8'),
  (48, 'CORDESVOCALES', 'CORDES VOCALES', 'hard', 'persone.testa.9'),
  (48, 'GORGE', null, 'easy', 'persone.testa.10'),
  (49, 'DIAPHRAGME', null, 'hard', 'persone.sistemi-corporei.0'),
  (49, 'VEINE', null, 'easy', 'persone.sistemi-corporei.1'),
  (49, 'ARTÈRE', null, 'medium', 'persone.sistemi-corporei.2'),
  (49, 'GLANDE', null, 'medium', 'persone.sistemi-corporei.3'),
  (49, 'NERF', null, 'easy', 'persone.sistemi-corporei.4'),
  (49, 'RESPIRATOIRE', null, 'hard', 'persone.sistemi-corporei.5'),
  (49, 'DIGESTIF', null, 'medium', 'persone.sistemi-corporei.6'),
  (49, 'CARDIOVASCULAIRE', 'CARDIO-VASCULAIRE', 'hard', 'persone.sistemi-corporei.7'),
  (49, 'LYMPHATIQUE', null, 'hard', 'persone.sistemi-corporei.8'),
  (49, 'URINAIRE', null, 'medium', 'persone.sistemi-corporei.9'),
  (49, 'ENDOCRINE', null, 'hard', 'persone.sistemi-corporei.10'),
  (49, 'NERVEUX', null, 'medium', 'persone.sistemi-corporei.11'),
  (49, 'REPRODUCTEUR', null, 'hard', 'persone.sistemi-corporei.12'),
  (50, 'OVAIRE', null, 'medium', 'persone.organi-riproduttivi.0'),
  (50, 'FOLLICULE', null, 'hard', 'persone.organi-riproduttivi.1'),
  (50, 'TROMPEDEFALLOPE', 'TROMPE DE FALLOPE', 'hard', 'persone.organi-riproduttivi.2'),
  (50, 'UTÉRUS', null, 'medium', 'persone.organi-riproduttivi.3'),
  (50, 'COLDELUTÉRUS', 'COL DE L''UTÉRUS', 'hard', 'persone.organi-riproduttivi.4'),
  (50, 'VAGIN', null, 'easy', 'persone.organi-riproduttivi.5'),
  (50, 'CLITORIS', null, 'medium', 'persone.organi-riproduttivi.6'),
  (50, 'LÈVRES', null, 'medium', 'persone.organi-riproduttivi.7'),
  (50, 'VESSIE', null, 'medium', 'persone.organi-riproduttivi.8');

insert into public.words (category_id, text, display, difficulty, concept_key) values
  (50, 'URÈTRE', null, 'medium', 'persone.organi-riproduttivi.9'),
  (50, 'PÉNIS', null, 'easy', 'persone.organi-riproduttivi.10'),
  (50, 'TESTICULE', null, 'hard', 'persone.organi-riproduttivi.11'),
  (50, 'SCROTUM', null, 'medium', 'persone.organi-riproduttivi.12'),
  (50, 'PRÉPUCE', null, 'medium', 'persone.organi-riproduttivi.13'),
  (50, 'PROSTATE', null, 'medium', 'persone.organi-riproduttivi.14'),
  (50, 'VÉSICULESÉMINALE', 'VÉSICULE SÉMINALE', 'hard', 'persone.organi-riproduttivi.15'),
  (50, 'CONDUITSPERMATIQUE', 'CONDUIT SPERMATIQUE', 'hard', 'persone.organi-riproduttivi.16'),
  (50, 'CONDUITÉJACULATOIRE', 'CONDUIT ÉJACULATOIRE', 'hard', 'persone.organi-riproduttivi.17'),
  (50, 'URETÈRE', null, 'medium', 'persone.organi-riproduttivi.18'),
  (50, 'RECTUM', null, 'medium', 'persone.organi-riproduttivi.19'),
  (50, 'HORMONE', null, 'medium', 'persone.organi-riproduttivi.20'),
  (50, 'SPERME', null, 'medium', 'persone.organi-riproduttivi.21'),
  (50, 'OEUF', null, 'easy', 'persone.organi-riproduttivi.22'),
  (50, 'RÈGLES', null, 'medium', 'persone.organi-riproduttivi.23'),
  (50, 'OVULATION', null, 'hard', 'persone.organi-riproduttivi.24'),
  (50, 'FÉCOND', null, 'medium', 'persone.organi-riproduttivi.25'),
  (50, 'STÉRILE', null, 'medium', 'persone.organi-riproduttivi.26'),
  (50, 'IMPUISSANT', null, 'hard', 'persone.organi-riproduttivi.27'),
  (50, 'CONCEVOIR', null, 'hard', 'persone.organi-riproduttivi.28'),
  (50, 'FERTILISATION', null, 'hard', 'persone.organi-riproduttivi.29'),
  (50, 'RAPPORTSSEXUELS', 'RAPPORTS SEXUELS', 'hard', 'persone.organi-riproduttivi.30'),
  (50, 'MASCULIN', null, 'medium', 'persone.organi-riproduttivi.31'),
  (50, 'FÉMININ', null, 'medium', 'persone.organi-riproduttivi.32'),
  (51, 'CONTRACEPTION', null, 'hard', 'persone.contraccezione.0'),
  (51, 'CONDOM', null, 'medium', 'persone.contraccezione.1'),
  (51, 'PILULE', null, 'medium', 'persone.contraccezione.2'),
  (51, 'DIAPHRAGME', null, 'hard', 'persone.contraccezione.3'),
  (51, 'PESSAIRE', null, 'medium', 'persone.contraccezione.4'),
  (51, 'CAPUCHONCERVICAL', 'CAPUCHON CERVICAL', 'hard', 'persone.contraccezione.5'),
  (51, 'STÉRILET', null, 'medium', 'persone.contraccezione.6'),
  (53, 'KÖRPER', null, 'medium', 'persone.corpo.0'),
  (53, 'KOPF', null, 'easy', 'persone.corpo.1'),
  (53, 'HALS', null, 'easy', 'persone.corpo.2'),
  (53, 'BRUST', null, 'easy', 'persone.corpo.3'),
  (53, 'BRUSTWARZE', null, 'hard', 'persone.corpo.5'),
  (53, 'BAUCH', null, 'easy', 'persone.corpo.6'),
  (53, 'TAILLE', null, 'medium', 'persone.corpo.7'),
  (53, 'NABEL', null, 'easy', 'persone.corpo.8'),
  (53, 'HÜFTE', null, 'easy', 'persone.corpo.9'),
  (53, 'UNTERARM', null, 'medium', 'persone.corpo.10'),
  (53, 'GESCHLECHTSTEILE', null, 'hard', 'persone.corpo.11'),
  (53, 'OBERSCHENKEL', null, 'hard', 'persone.corpo.12'),
  (53, 'LEISTE', null, 'medium', 'persone.corpo.13'),
  (53, 'KNIE', null, 'easy', 'persone.corpo.14'),
  (53, 'BEIN', null, 'easy', 'persone.corpo.15'),
  (53, 'SCHIENBEIN', null, 'hard', 'persone.corpo.16'),
  (53, 'RÜCKEN', null, 'medium', 'persone.corpo.17'),
  (53, 'NACKEN', null, 'medium', 'persone.corpo.18'),
  (53, 'SCHULTER', null, 'medium', 'persone.corpo.19'),
  (53, 'ACHSELHÖHLE', null, 'hard', 'persone.corpo.20'),
  (53, 'ARM', null, 'easy', 'persone.corpo.21'),
  (53, 'ELLBOGEN', null, 'medium', 'persone.corpo.22'),
  (53, 'HINTERBACKE', null, 'hard', 'persone.corpo.23'),
  (53, 'HAND', null, 'easy', 'persone.corpo.24'),
  (53, 'WADE', null, 'easy', 'persone.corpo.25'),
  (53, 'KNÖCHEL', null, 'medium', 'persone.corpo.26'),
  (53, 'FERSE', null, 'easy', 'persone.corpo.27'),
  (53, 'FUSS', null, 'easy', 'persone.corpo.28'),
  (53, 'MANN', null, 'easy', 'persone.corpo.29'),
  (53, 'FRAU', null, 'easy', 'persone.corpo.30'),
  (54, 'GESICHT', null, 'medium', 'persone.viso.0'),
  (54, 'HAAR', null, 'easy', 'persone.viso.1'),
  (54, 'HAUT', null, 'easy', 'persone.viso.2'),
  (54, 'STIRN', null, 'easy', 'persone.viso.3'),
  (54, 'AUGENBRAUE', null, 'hard', 'persone.viso.4'),
  (54, 'SCHLÄFE', null, 'medium', 'persone.viso.5'),
  (54, 'WIMPER', null, 'medium', 'persone.viso.6'),
  (54, 'AUGE', null, 'easy', 'persone.viso.7'),
  (54, 'OHR', null, 'easy', 'persone.viso.8'),
  (54, 'BACKE', null, 'easy', 'persone.viso.9'),
  (54, 'NASE', null, 'easy', 'persone.viso.10'),
  (54, 'NASENLOCH', null, 'hard', 'persone.viso.11'),
  (54, 'MUTTERMAL', null, 'hard', 'persone.viso.12'),
  (54, 'MUND', null, 'easy', 'persone.viso.13'),
  (54, 'LIPPE', null, 'easy', 'persone.viso.14'),
  (54, 'KINNLADE', null, 'medium', 'persone.viso.15'),
  (54, 'KINN', null, 'easy', 'persone.viso.16'),
  (54, 'FALTE', null, 'easy', 'persone.viso.17'),
  (54, 'SOMMERSPROSSE', null, 'hard', 'persone.viso.18'),
  (54, 'GRÜBCHEN', null, 'medium', 'persone.viso.19'),
  (54, 'PORE', null, 'easy', 'persone.viso.20'),
  (55, 'HAND', null, 'easy', 'persone.mano.0'),
  (55, 'FINGER', null, 'medium', 'persone.mano.1'),
  (55, 'DAUMEN', null, 'medium', 'persone.mano.2'),
  (55, 'ZEIGEFINGER', null, 'hard', 'persone.mano.3'),
  (55, 'MITTELFINGER', null, 'hard', 'persone.mano.4'),
  (55, 'RINGFINGER', null, 'hard', 'persone.mano.5'),
  (55, 'KLEINERFINGER', 'KLEINER FINGER', 'hard', 'persone.mano.6'),
  (55, 'HANDFLÄCHE', null, 'hard', 'persone.mano.7'),
  (55, 'KNÖCHEL', null, 'medium', 'persone.mano.8'),
  (55, 'FINGERNAGEL', null, 'hard', 'persone.mano.9'),
  (55, 'NAGELHAUT', null, 'hard', 'persone.mano.10'),
  (55, 'FAUST', null, 'easy', 'persone.mano.11'),
  (55, 'HANDGELENK', null, 'hard', 'persone.mano.12'),
  (56, 'FUSS', null, 'easy', 'persone.piede.0'),
  (56, 'BALLEN', null, 'medium', 'persone.piede.1'),
  (56, 'ZEH', null, 'easy', 'persone.piede.2'),
  (56, 'FERSE', null, 'easy', 'persone.piede.3'),
  (56, 'FUSSSOHLE', null, 'hard', 'persone.piede.4');

insert into public.words (category_id, text, display, difficulty, concept_key) values
  (56, 'SPANN', null, 'easy', 'persone.piede.5'),
  (56, 'GEWÖLBE', null, 'medium', 'persone.piede.6'),
  (56, 'GROSSEZEH', 'GROSSE ZEH', 'hard', 'persone.piede.7'),
  (56, 'ZEHENNAGEL', null, 'hard', 'persone.piede.8'),
  (56, 'KLEINERZEH', 'KLEINER ZEH', 'hard', 'persone.piede.9'),
  (56, 'KNÖCHEL', null, 'medium', 'persone.piede.10'),
  (57, 'MUSKEL', null, 'medium', 'persone.muscoli.0'),
  (57, 'STIRNMUSKEL', null, 'hard', 'persone.muscoli.1'),
  (57, 'BRUSTMUSKEL', null, 'hard', 'persone.muscoli.2'),
  (57, 'DELTAMUSKEL', null, 'hard', 'persone.muscoli.3'),
  (57, 'KAPUZENMUSKEL', null, 'hard', 'persone.muscoli.4'),
  (57, 'ZWISCHENRIPPENMUSKEL', null, 'hard', 'persone.muscoli.5'),
  (57, 'RÜCKENMUSKEL', null, 'hard', 'persone.muscoli.6'),
  (57, 'BIZEPS', null, 'medium', 'persone.muscoli.7'),
  (57, 'TRIZEPS', null, 'medium', 'persone.muscoli.8'),
  (57, 'BAUCHMUSKELN', null, 'hard', 'persone.muscoli.9'),
  (57, 'GESÄSSMUSKEL', null, 'hard', 'persone.muscoli.10'),
  (57, 'OBERSCHENKELMUSKELN', null, 'hard', 'persone.muscoli.11'),
  (57, 'ACHILLESSEHNE', null, 'hard', 'persone.muscoli.12'),
  (58, 'SKELETT', null, 'medium', 'persone.scheletro.0'),
  (58, 'KNOCHEN', null, 'medium', 'persone.scheletro.1'),
  (58, 'SCHÄDEL', null, 'medium', 'persone.scheletro.2'),
  (58, 'SCHLÜSSELBEIN', null, 'hard', 'persone.scheletro.3'),
  (58, 'SCHULTERBLATT', null, 'hard', 'persone.scheletro.4'),
  (58, 'WIRBELSÄULE', null, 'hard', 'persone.scheletro.5'),
  (58, 'BECKEN', null, 'medium', 'persone.scheletro.6'),
  (58, 'STEISSBEIN', null, 'hard', 'persone.scheletro.7'),
  (58, 'OBERARMKNOCHEN', null, 'hard', 'persone.scheletro.8'),
  (58, 'SPEICHE', null, 'medium', 'persone.scheletro.9'),
  (58, 'ELLE', null, 'easy', 'persone.scheletro.10'),
  (58, 'OBERSCHENKELKNOCHEN', null, 'hard', 'persone.scheletro.11'),
  (58, 'KNIESCHEIBE', null, 'hard', 'persone.scheletro.12'),
  (58, 'SCHIENBEIN', null, 'hard', 'persone.scheletro.13'),
  (58, 'WADENBEIN', null, 'hard', 'persone.scheletro.14'),
  (58, 'RIPPE', null, 'easy', 'persone.scheletro.15'),
  (58, 'BRUSTKORB', null, 'hard', 'persone.scheletro.16'),
  (58, 'BRUSTBEIN', null, 'hard', 'persone.scheletro.17'),
  (58, 'HALSWIRBEL', null, 'hard', 'persone.scheletro.18'),
  (58, 'BRUSTWIRBEL', null, 'hard', 'persone.scheletro.19'),
  (58, 'LENDENWIRBEL', null, 'hard', 'persone.scheletro.20'),
  (58, 'GELENK', null, 'medium', 'persone.scheletro.21'),
  (58, 'SEHNENBAND', null, 'hard', 'persone.scheletro.22'),
  (58, 'SEHNE', null, 'easy', 'persone.scheletro.23'),
  (58, 'MITTELHANDKNOCHEN', null, 'hard', 'persone.scheletro.24'),
  (58, 'MITTELFUSSKNOCHEN', null, 'hard', 'persone.scheletro.25'),
  (58, 'KNORPEL', null, 'medium', 'persone.scheletro.26'),
  (59, 'HERZ', null, 'easy', 'persone.organi-interni.0'),
  (59, 'LUNGE', null, 'easy', 'persone.organi-interni.1'),
  (59, 'LEBER', null, 'easy', 'persone.organi-interni.2'),
  (59, 'MAGEN', null, 'easy', 'persone.organi-interni.3'),
  (59, 'NIERE', null, 'easy', 'persone.organi-interni.4'),
  (59, 'MILZ', null, 'easy', 'persone.organi-interni.5'),
  (59, 'BAUCHSPEICHELDRÜSE', null, 'hard', 'persone.organi-interni.6'),
  (59, 'SCHILDDRÜSE', null, 'hard', 'persone.organi-interni.7'),
  (59, 'LUFTRÖHRE', null, 'hard', 'persone.organi-interni.8'),
  (59, 'ZWÖLFFINGERDARM', null, 'hard', 'persone.organi-interni.9'),
  (59, 'DÜNNDARM', null, 'medium', 'persone.organi-interni.10'),
  (59, 'DICKDARM', null, 'medium', 'persone.organi-interni.11'),
  (59, 'BLINDDARM', null, 'hard', 'persone.organi-interni.12'),
  (60, 'GEHIRN', null, 'medium', 'persone.testa.0'),
  (60, 'SINUS', null, 'easy', 'persone.testa.1'),
  (60, 'GAUMEN', null, 'medium', 'persone.testa.2'),
  (60, 'RACHEN', null, 'medium', 'persone.testa.3'),
  (60, 'ZUNGE', null, 'easy', 'persone.testa.4'),
  (60, 'KEHLDECKEL', null, 'hard', 'persone.testa.5'),
  (60, 'KEHLKOPF', null, 'medium', 'persone.testa.6'),
  (60, 'SPEISERÖHRE', null, 'hard', 'persone.testa.7'),
  (60, 'ADAMSAPFEL', null, 'hard', 'persone.testa.8'),
  (60, 'STIMMBÄNDER', null, 'hard', 'persone.testa.9'),
  (60, 'KEHLE', null, 'easy', 'persone.testa.10'),
  (61, 'ZWERCHFELL', null, 'hard', 'persone.sistemi-corporei.0'),
  (61, 'VENE', null, 'easy', 'persone.sistemi-corporei.1'),
  (61, 'ARTERIE', null, 'medium', 'persone.sistemi-corporei.2'),
  (61, 'DRÜSE', null, 'easy', 'persone.sistemi-corporei.3'),
  (61, 'NERV', null, 'easy', 'persone.sistemi-corporei.4'),
  (61, 'ATMUNGSSYSTEM', null, 'hard', 'persone.sistemi-corporei.5'),
  (61, 'VERDAUUNGSSYSTEM', null, 'hard', 'persone.sistemi-corporei.6'),
  (61, 'KREISLAUFSYSTEM', null, 'hard', 'persone.sistemi-corporei.7'),
  (61, 'LYMPHATISCHESSYSTEM', 'LYMPHATISCHES SYSTEM', 'hard', 'persone.sistemi-corporei.8'),
  (61, 'HARNSYSTEM', null, 'hard', 'persone.sistemi-corporei.9'),
  (61, 'ENDOKRINESSYSTEM', 'ENDOKRINES SYSTEM', 'hard', 'persone.sistemi-corporei.10'),
  (61, 'NERVENSYSTEM', null, 'hard', 'persone.sistemi-corporei.11'),
  (61, 'FORTPFLANZUNGSSYSTEM', null, 'hard', 'persone.sistemi-corporei.12'),
  (62, 'EIERSTOCK', null, 'hard', 'persone.organi-riproduttivi.0'),
  (62, 'FOLLIKEL', null, 'medium', 'persone.organi-riproduttivi.1'),
  (62, 'EILEITER', null, 'medium', 'persone.organi-riproduttivi.2'),
  (62, 'GEBÄRMUTTER', null, 'hard', 'persone.organi-riproduttivi.3'),
  (62, 'GEBÄRMUTTERHALS', null, 'hard', 'persone.organi-riproduttivi.4'),
  (62, 'SCHEIDE', null, 'medium', 'persone.organi-riproduttivi.5'),
  (62, 'KLITORIS', null, 'medium', 'persone.organi-riproduttivi.6'),
  (62, 'SCHAMLIPPEN', null, 'hard', 'persone.organi-riproduttivi.7'),
  (62, 'BLASE', null, 'easy', 'persone.organi-riproduttivi.8'),
  (62, 'HARNRÖHRE', null, 'hard', 'persone.organi-riproduttivi.9'),
  (62, 'PENIS', null, 'easy', 'persone.organi-riproduttivi.10'),
  (62, 'HODEN', null, 'easy', 'persone.organi-riproduttivi.11'),
  (62, 'HODENSACK', null, 'hard', 'persone.organi-riproduttivi.12'),
  (62, 'VORHAUT', null, 'medium', 'persone.organi-riproduttivi.13'),
  (62, 'PROSTATA', null, 'medium', 'persone.organi-riproduttivi.14'),
  (62, 'SAMENBLÄSCHEN', null, 'hard', 'persone.organi-riproduttivi.15'),
  (62, 'SAMENLEITER', null, 'hard', 'persone.organi-riproduttivi.16');

insert into public.words (category_id, text, display, difficulty, concept_key) values
  (62, 'SAMENAUSFÜHRUNGSGANG', null, 'hard', 'persone.organi-riproduttivi.17'),
  (62, 'HARNLEITER', null, 'hard', 'persone.organi-riproduttivi.18'),
  (62, 'MASTDARM', null, 'medium', 'persone.organi-riproduttivi.19'),
  (62, 'HORMON', null, 'medium', 'persone.organi-riproduttivi.20'),
  (62, 'SPERMIUM', null, 'medium', 'persone.organi-riproduttivi.21'),
  (62, 'EI', null, 'easy', 'persone.organi-riproduttivi.22'),
  (62, 'MENSTRUATION', null, 'hard', 'persone.organi-riproduttivi.23'),
  (62, 'EISPRUNG', null, 'medium', 'persone.organi-riproduttivi.24'),
  (62, 'FRUCHTBAR', null, 'hard', 'persone.organi-riproduttivi.25'),
  (62, 'STERIL', null, 'medium', 'persone.organi-riproduttivi.26'),
  (62, 'IMPOTENT', null, 'medium', 'persone.organi-riproduttivi.27'),
  (62, 'EMPFANGEN', null, 'hard', 'persone.organi-riproduttivi.28'),
  (62, 'BEFRUCHTUNG', null, 'hard', 'persone.organi-riproduttivi.29'),
  (62, 'GESCHLECHTSVERKEHR', null, 'hard', 'persone.organi-riproduttivi.30'),
  (62, 'MÄNNLICH', null, 'medium', 'persone.organi-riproduttivi.31'),
  (62, 'WEIBLICH', null, 'medium', 'persone.organi-riproduttivi.32'),
  (63, 'EMPFÄNGNISVERHÜTUNG', null, 'hard', 'persone.contraccezione.0'),
  (63, 'KONDOM', null, 'medium', 'persone.contraccezione.1'),
  (63, 'PILLE', null, 'easy', 'persone.contraccezione.2'),
  (63, 'DIAPHRAGMA', null, 'hard', 'persone.contraccezione.3'),
  (63, 'PESSAR', null, 'medium', 'persone.contraccezione.4'),
  (63, 'KAPPE', null, 'easy', 'persone.contraccezione.5'),
  (63, 'SPIRALE', null, 'medium', 'persone.contraccezione.6'),
  (65, 'CUERPO', null, 'medium', 'persone.corpo.0'),
  (65, 'CABEZA', null, 'medium', 'persone.corpo.1'),
  (65, 'CUELLO', null, 'medium', 'persone.corpo.2'),
  (65, 'PECHO', null, 'easy', 'persone.corpo.3'),
  (65, 'PEZÓN', null, 'easy', 'persone.corpo.5'),
  (65, 'ABDOMEN', null, 'medium', 'persone.corpo.6'),
  (65, 'CINTURA', null, 'medium', 'persone.corpo.7'),
  (65, 'OMBLIGO', null, 'medium', 'persone.corpo.8'),
  (65, 'CADERA', null, 'medium', 'persone.corpo.9'),
  (65, 'ANTEBRAZO', null, 'hard', 'persone.corpo.10'),
  (65, 'GENITALES', null, 'hard', 'persone.corpo.11'),
  (65, 'MUSLO', null, 'easy', 'persone.corpo.12'),
  (65, 'INGLE', null, 'easy', 'persone.corpo.13'),
  (65, 'RODILLA', null, 'medium', 'persone.corpo.14'),
  (65, 'PIERNA', null, 'medium', 'persone.corpo.15'),
  (65, 'ESPINILLA', null, 'hard', 'persone.corpo.16'),
  (65, 'ESPALDA', null, 'medium', 'persone.corpo.17'),
  (65, 'NUCA', null, 'easy', 'persone.corpo.18'),
  (65, 'HOMBRO', null, 'medium', 'persone.corpo.19'),
  (65, 'AXILA', null, 'easy', 'persone.corpo.20'),
  (65, 'BRAZO', null, 'easy', 'persone.corpo.21'),
  (65, 'CODO', null, 'easy', 'persone.corpo.22'),
  (65, 'NALGA', null, 'easy', 'persone.corpo.23'),
  (65, 'MANO', null, 'easy', 'persone.corpo.24'),
  (65, 'PANTORRILLA', null, 'hard', 'persone.corpo.25'),
  (65, 'TOBILLO', null, 'medium', 'persone.corpo.26'),
  (65, 'TALÓN', null, 'easy', 'persone.corpo.27'),
  (65, 'PIE', null, 'easy', 'persone.corpo.28'),
  (65, 'HOMBRE', null, 'medium', 'persone.corpo.29'),
  (65, 'MUJER', null, 'easy', 'persone.corpo.30'),
  (66, 'CARA', null, 'easy', 'persone.viso.0'),
  (66, 'CABELLO', null, 'medium', 'persone.viso.1'),
  (66, 'PIEL', null, 'easy', 'persone.viso.2'),
  (66, 'FRENTE', null, 'medium', 'persone.viso.3'),
  (66, 'CEJA', null, 'easy', 'persone.viso.4'),
  (66, 'SIEN', null, 'easy', 'persone.viso.5'),
  (66, 'PESTAÑA', null, 'medium', 'persone.viso.6'),
  (66, 'OJO', null, 'easy', 'persone.viso.7'),
  (66, 'OREJA', null, 'easy', 'persone.viso.8'),
  (66, 'MEJILLA', null, 'medium', 'persone.viso.9'),
  (66, 'NARIZ', null, 'easy', 'persone.viso.10'),
  (66, 'FOSANASAL', 'FOSA NASAL', 'hard', 'persone.viso.11'),
  (66, 'LUNAR', null, 'easy', 'persone.viso.12'),
  (66, 'BOCA', null, 'easy', 'persone.viso.13'),
  (66, 'LABIO', null, 'easy', 'persone.viso.14'),
  (66, 'MANDÍBULA', null, 'hard', 'persone.viso.15'),
  (66, 'BARBILLA', null, 'medium', 'persone.viso.16'),
  (66, 'ARRUGA', null, 'medium', 'persone.viso.17'),
  (66, 'PECA', null, 'easy', 'persone.viso.18'),
  (66, 'HOYUELO', null, 'medium', 'persone.viso.19'),
  (66, 'PORO', null, 'easy', 'persone.viso.20'),
  (67, 'MANO', null, 'easy', 'persone.mano.0'),
  (67, 'DEDO', null, 'easy', 'persone.mano.1'),
  (67, 'PULGAR', null, 'medium', 'persone.mano.2'),
  (67, 'ÍNDICE', null, 'medium', 'persone.mano.3'),
  (67, 'DEDOCORAZÓN', 'DEDO CORAZÓN', 'hard', 'persone.mano.4'),
  (67, 'ANULAR', null, 'medium', 'persone.mano.5'),
  (67, 'MEÑIQUE', null, 'medium', 'persone.mano.6'),
  (67, 'PALMA', null, 'easy', 'persone.mano.7'),
  (67, 'NUDILLO', null, 'medium', 'persone.mano.8'),
  (67, 'UÑA', null, 'easy', 'persone.mano.9'),
  (67, 'CUTÍCULA', null, 'medium', 'persone.mano.10'),
  (67, 'PUÑO', null, 'easy', 'persone.mano.11'),
  (67, 'MUÑECA', null, 'medium', 'persone.mano.12'),
  (68, 'PIE', null, 'easy', 'persone.piede.0'),
  (68, 'ANTEPIÉ', null, 'medium', 'persone.piede.1'),
  (68, 'DEDODELPIE', 'DEDO DEL PIE', 'hard', 'persone.piede.2'),
  (68, 'TALÓN', null, 'easy', 'persone.piede.3'),
  (68, 'PLANTADELPIE', 'PLANTA DEL PIE', 'hard', 'persone.piede.4'),
  (68, 'EMPEINE', null, 'medium', 'persone.piede.5'),
  (68, 'ARCOPLANTAR', 'ARCO PLANTAR', 'hard', 'persone.piede.6'),
  (68, 'DEDOGORDO', 'DEDO GORDO', 'hard', 'persone.piede.7'),
  (68, 'UÑADELPIE', 'UÑA DEL PIE', 'hard', 'persone.piede.8'),
  (68, 'DEDOPEQUEÑO', 'DEDO PEQUEÑO', 'hard', 'persone.piede.9'),
  (68, 'TOBILLO', null, 'medium', 'persone.piede.10'),
  (69, 'MÚSCULO', null, 'medium', 'persone.muscoli.0'),
  (69, 'FRONTAL', null, 'medium', 'persone.muscoli.1');

insert into public.words (category_id, text, display, difficulty, concept_key) values
  (69, 'PECTORAL', null, 'medium', 'persone.muscoli.2'),
  (69, 'DELTOIDES', null, 'hard', 'persone.muscoli.3'),
  (69, 'TRAPECIO', null, 'medium', 'persone.muscoli.4'),
  (69, 'INTERCOSTAL', null, 'hard', 'persone.muscoli.5'),
  (69, 'DORSAL', null, 'medium', 'persone.muscoli.6'),
  (69, 'BÍCEPS', null, 'medium', 'persone.muscoli.7'),
  (69, 'TRÍCEPS', null, 'medium', 'persone.muscoli.8'),
  (69, 'ABDOMINALES', null, 'hard', 'persone.muscoli.9'),
  (69, 'GLÚTEO', null, 'medium', 'persone.muscoli.10'),
  (69, 'CUÁDRICEPS', null, 'hard', 'persone.muscoli.11'),
  (69, 'TENDÓNDEAQUILES', 'TENDÓN DE AQUILES', 'hard', 'persone.muscoli.12'),
  (70, 'ESQUELETO', null, 'hard', 'persone.scheletro.0'),
  (70, 'HUESO', null, 'easy', 'persone.scheletro.1'),
  (70, 'CRÁNEO', null, 'medium', 'persone.scheletro.2'),
  (70, 'CLAVÍCULA', null, 'hard', 'persone.scheletro.3'),
  (70, 'ESCÁPULA', null, 'medium', 'persone.scheletro.4'),
  (70, 'ESPINADORSAL', 'ESPINA DORSAL', 'hard', 'persone.scheletro.5'),
  (70, 'PELVIS', null, 'medium', 'persone.scheletro.6'),
  (70, 'COXIS', null, 'easy', 'persone.scheletro.7'),
  (70, 'HÚMERO', null, 'medium', 'persone.scheletro.8'),
  (70, 'RADIO', null, 'easy', 'persone.scheletro.9'),
  (70, 'CÚBITO', null, 'medium', 'persone.scheletro.10'),
  (70, 'FÉMUR', null, 'easy', 'persone.scheletro.11'),
  (70, 'RÓTULA', null, 'medium', 'persone.scheletro.12'),
  (70, 'TIBIA', null, 'easy', 'persone.scheletro.13'),
  (70, 'PERONÉ', null, 'medium', 'persone.scheletro.14'),
  (70, 'COSTILLA', null, 'medium', 'persone.scheletro.15'),
  (70, 'CAJATORÁCICA', 'CAJA TORÁCICA', 'hard', 'persone.scheletro.16'),
  (70, 'ESTERNÓN', null, 'medium', 'persone.scheletro.17'),
  (70, 'VÉRTEBRASCERVICALES', 'VÉRTEBRAS CERVICALES', 'hard', 'persone.scheletro.18'),
  (70, 'VÉRTEBRASDORSALES', 'VÉRTEBRAS DORSALES', 'hard', 'persone.scheletro.19'),
  (70, 'VÉRTEBRASLUMBARES', 'VÉRTEBRAS LUMBARES', 'hard', 'persone.scheletro.20'),
  (70, 'ARTICULACIÓN', null, 'hard', 'persone.scheletro.21'),
  (70, 'LIGAMENTO', null, 'hard', 'persone.scheletro.22'),
  (70, 'TENDÓN', null, 'medium', 'persone.scheletro.23'),
  (70, 'METACARPO', null, 'hard', 'persone.scheletro.24'),
  (70, 'METATARSO', null, 'hard', 'persone.scheletro.25'),
  (70, 'CARTÍLAGO', null, 'hard', 'persone.scheletro.26'),
  (71, 'CORAZÓN', null, 'medium', 'persone.organi-interni.0'),
  (71, 'PULMÓN', null, 'medium', 'persone.organi-interni.1'),
  (71, 'HÍGADO', null, 'medium', 'persone.organi-interni.2'),
  (71, 'ESTÓMAGO', null, 'medium', 'persone.organi-interni.3'),
  (71, 'RIÑÓN', null, 'easy', 'persone.organi-interni.4'),
  (71, 'BAZO', null, 'easy', 'persone.organi-interni.5'),
  (71, 'PÁNCREAS', null, 'medium', 'persone.organi-interni.6'),
  (71, 'TIROIDES', null, 'medium', 'persone.organi-interni.7'),
  (71, 'TRÁQUEA', null, 'medium', 'persone.organi-interni.8'),
  (71, 'DUODENO', null, 'medium', 'persone.organi-interni.9'),
  (71, 'INTESTINODELGADO', 'INTESTINO DELGADO', 'hard', 'persone.organi-interni.10'),
  (71, 'INTESTINOGRUESO', 'INTESTINO GRUESO', 'hard', 'persone.organi-interni.11'),
  (71, 'APÉNDICE', null, 'medium', 'persone.organi-interni.12'),
  (72, 'CEREBRO', null, 'medium', 'persone.testa.0'),
  (72, 'SENO', null, 'easy', 'persone.testa.1'),
  (72, 'PALADAR', null, 'medium', 'persone.testa.2'),
  (72, 'FARINGE', null, 'medium', 'persone.testa.3'),
  (72, 'LENGUA', null, 'medium', 'persone.testa.4'),
  (72, 'EPIGLOTIS', null, 'hard', 'persone.testa.5'),
  (72, 'LARINGE', null, 'medium', 'persone.testa.6'),
  (72, 'ESÓFAGO', null, 'medium', 'persone.testa.7'),
  (72, 'MANZANADEADÁN', 'MANZANA DE ADÁN', 'hard', 'persone.testa.8'),
  (72, 'CUERDASVOCALES', 'CUERDAS VOCALES', 'hard', 'persone.testa.9'),
  (72, 'GARGANTA', null, 'medium', 'persone.testa.10'),
  (73, 'DIAFRAGMA', null, 'hard', 'persone.sistemi-corporei.0'),
  (73, 'VENA', null, 'easy', 'persone.sistemi-corporei.1'),
  (73, 'ARTERIA', null, 'medium', 'persone.sistemi-corporei.2'),
  (73, 'GLÁNDULA', null, 'medium', 'persone.sistemi-corporei.3'),
  (73, 'NERVIO', null, 'medium', 'persone.sistemi-corporei.4'),
  (73, 'RESPIRATORIO', null, 'hard', 'persone.sistemi-corporei.5'),
  (73, 'DIGESTIVO', null, 'hard', 'persone.sistemi-corporei.6'),
  (73, 'CARDIOVASCULAR', null, 'hard', 'persone.sistemi-corporei.7'),
  (73, 'LINFÁTICO', null, 'hard', 'persone.sistemi-corporei.8'),
  (73, 'URINARIO', null, 'medium', 'persone.sistemi-corporei.9'),
  (73, 'ENDOCRINO', null, 'hard', 'persone.sistemi-corporei.10'),
  (73, 'NERVIOSO', null, 'medium', 'persone.sistemi-corporei.11'),
  (73, 'REPRODUCTOR', null, 'hard', 'persone.sistemi-corporei.12'),
  (74, 'OVARIO', null, 'medium', 'persone.organi-riproduttivi.0'),
  (74, 'FOLÍCULO', null, 'medium', 'persone.organi-riproduttivi.1'),
  (74, 'TROMPADEFALOPIO', 'TROMPA DE FALOPIO', 'hard', 'persone.organi-riproduttivi.2'),
  (74, 'ÚTERO', null, 'easy', 'persone.organi-riproduttivi.3'),
  (74, 'CUELLOUTERINO', 'CUELLO UTERINO', 'hard', 'persone.organi-riproduttivi.4'),
  (74, 'VAGINA', null, 'medium', 'persone.organi-riproduttivi.5'),
  (74, 'CLÍTORIS', null, 'medium', 'persone.organi-riproduttivi.6'),
  (74, 'LABIOS', null, 'medium', 'persone.organi-riproduttivi.7'),
  (74, 'VEJIGA', null, 'medium', 'persone.organi-riproduttivi.8'),
  (74, 'URETRA', null, 'medium', 'persone.organi-riproduttivi.9'),
  (74, 'PENE', null, 'easy', 'persone.organi-riproduttivi.10'),
  (74, 'TESTÍCULO', null, 'hard', 'persone.organi-riproduttivi.11'),
  (74, 'ESCROTO', null, 'medium', 'persone.organi-riproduttivi.12'),
  (74, 'PREPUCIO', null, 'medium', 'persone.organi-riproduttivi.13'),
  (74, 'PRÓSTATA', null, 'medium', 'persone.organi-riproduttivi.14'),
  (74, 'VESÍCULASEMINAL', 'VESÍCULA SEMINAL', 'hard', 'persone.organi-riproduttivi.15'),
  (74, 'CONDUCTODEFERENTE', 'CONDUCTO DEFERENTE', 'hard', 'persone.organi-riproduttivi.16'),
  (74, 'CONDUCTOEYACULADOR', 'CONDUCTO EYACULADOR', 'hard', 'persone.organi-riproduttivi.17'),
  (74, 'URÉTER', null, 'medium', 'persone.organi-riproduttivi.18'),
  (74, 'RECTO', null, 'easy', 'persone.organi-riproduttivi.19'),
  (74, 'HORMONA', null, 'medium', 'persone.organi-riproduttivi.20'),
  (74, 'ESPERMA', null, 'medium', 'persone.organi-riproduttivi.21'),
  (74, 'ÓVULO', null, 'easy', 'persone.organi-riproduttivi.22'),
  (74, 'MENSTRUACIÓN', null, 'hard', 'persone.organi-riproduttivi.23'),
  (74, 'OVULACIÓN', null, 'hard', 'persone.organi-riproduttivi.24');

insert into public.words (category_id, text, display, difficulty, concept_key) values
  (74, 'FÉRTIL', null, 'medium', 'persone.organi-riproduttivi.25'),
  (74, 'ESTÉRIL', null, 'medium', 'persone.organi-riproduttivi.26'),
  (74, 'IMPOTENTE', null, 'hard', 'persone.organi-riproduttivi.27'),
  (74, 'CONCEBIR', null, 'medium', 'persone.organi-riproduttivi.28'),
  (74, 'FERTILIZACIÓN', null, 'hard', 'persone.organi-riproduttivi.29'),
  (74, 'COITO', null, 'easy', 'persone.organi-riproduttivi.30'),
  (74, 'MASCULINO', null, 'hard', 'persone.organi-riproduttivi.31'),
  (74, 'FEMENINO', null, 'medium', 'persone.organi-riproduttivi.32'),
  (75, 'ANTICONCEPCIÓN', null, 'hard', 'persone.contraccezione.0'),
  (75, 'CONDÓN', null, 'medium', 'persone.contraccezione.1'),
  (75, 'PASTILLA', null, 'medium', 'persone.contraccezione.2'),
  (75, 'DIAFRAGMA', null, 'hard', 'persone.contraccezione.3'),
  (75, 'PESARIO', null, 'medium', 'persone.contraccezione.4'),
  (75, 'CAPUCHÓNCERVICAL', 'CAPUCHÓN CERVICAL', 'hard', 'persone.contraccezione.5'),
  (75, 'DISPOSITIVOINTRAUTERINO', 'DISPOSITIVO INTRAUTERINO', 'hard', 'persone.contraccezione.6');

select setval(pg_get_serial_sequence('public.categories', 'id'), (select coalesce(max(id), 1) from public.categories));
select setval(pg_get_serial_sequence('public.words', 'id'), (select coalesce(max(id), 1) from public.words));

commit;
